---
- name: Remove a user from the range
  gather_facts: true
  hosts: localhost
  become: true
  tasks:
    - name: Remove the ludus user directory for user
      become: false
      ansible.builtin.file:
        path: "{{ ludus_users_dir }}/{{ username }}"
        state: absent

    - name: Remove the user from the remote host
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /bin/bash
        state: absent
        remove: true

    - name: Check for wg client public key
      ansible.builtin.stat:
        path: /etc/wireguard/{{ user_id }}-client-public-key
      register: wg_client_public_key_stat

    - name: Get wg client public key
      ansible.builtin.slurp:
        src: /etc/wireguard/{{ user_id }}-client-public-key
      register: wg_client_public_key_slurp
      when: wg_client_public_key_stat.stat.exists

    - name: Set the client key fact
      ansible.builtin.set_fact:
        client_public_key: "{{ wg_client_public_key_slurp['content'] | b64decode | trim }}"
      when: wg_client_public_key_stat.stat.exists

    - name: Remove the user from wireguard
      ansible.builtin.blockinfile:
        path: /etc/wireguard/wg0.conf
        block: |
          [Peer]
          PublicKey = {{ client_public_key }}
          AllowedIPs = 198.51.100.{{ user_number }}/32
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR {{ user_id }}"
        state: absent
      when: wg_client_public_key_stat.stat.exists

    - name: Remove wireguard public key
      ansible.builtin.file:
        path: "/etc/wireguard/{{ user_id }}-client-public-key"
        state: absent

    - name: Remove wireguard private key
      ansible.builtin.file:
        path: "/etc/wireguard/{{ user_id }}-client-private-key"
        state: absent

    - name: Remove wireguard config
      ansible.builtin.file:
        path: "/etc/wireguard/{{ user_id }}_client.conf"
        state: absent

    # This can be used to sync the config, but it causes a hiccup in all client's connections
    # Use the sync below instead
    # - name: Restart wireguard
    #   ansible.builtin.service:
    #     name: wg-quick@wg0
    #     state: restarted

    - name: Sync the wireguard config
      ansible.builtin.shell: |
        wg syncconf wg0 <(wg-quick strip wg0)
      args:
        executable: /bin/bash
      when: wg_client_public_key_stat.stat.exists

    # - name: Remove the portforward for this user (Enterprise)
    #   ansible.builtin.include_tasks: portforward-management.yml
    #   vars:
    #     port_to_forward_on_ludus_host: "{{ 51000 + range_second_octet }}"
    #     host_to_forward_to: "192.0.2.{{ 100 + range_second_octet }}"
    #     port_to_forward_to: 51820
    #     state_var: absent
    #   when:
    #     - ludus_enterprise_license is defined and ludus_enterprise_license
    #     - lookup('ansible.builtin.fileglob', playbook_dir + '/portforward-management.yml') != []
