// Autogenerated by github.com/nedieyassin/pocketbase-gogen.
// Please feel free to edit after noting the explanation:
//
// This file is an intermediate product of the proxy generation.
// It is called a 'schema as code' or just 'template'. It is not meant to be
// compiled it is only meant for human interaction, place it in a separate package
// but never import it.
// Here's what you can do to influence the final code generation step:
//
// Do:
//   - Edit the struct names. The names are directly copied to the proxy struct definitions.
//   - Remove structs or fields that you don't want in the generated code. Note that upon removing a struct
//     you also have to remove any fields that have that struct as their type.
//   - Edit the type name in the '// select:' comments.
//   - Change the const names of the select options by adding a pair of [] to the // select: comment.
//     Example: // select: MySelectType(optionA, optionB)[OpA, OpB] <-- These constants will represent
//     the select options (like an enum). If you omit the [] the option names are used directly.
//   - Edit the field names. If you do, the generator still needs to know the original database field name.
//     To provide this, add a '// schema-name: [original field name]' comment directly above the field.
//   - Add methods to the template structs. The generator will replace any fields you access with the also
//     generated getters/setters. Be aware of that when repeatedly assigning a template field. You are
//     calling a setter on every assignment. The methods can also call each other.
//
// Do not:
//   - Add structs that do not represent a PB collection.
//   - Add fields that are not part of the PB schema to the structs.
//   - Change the '// collection-name:' comments unless the collection was actually renamed.
//     If the comment is missing from the first struct field, the generator will print a warning.
//   - Change the select values in the () of the '// select:' comments'
//   - Remove the '// system:' doc comments from the system fields. Generation will fail if you do so.
//   - Shadow any names from the core.Record struct. Generation will also fail for safety.
//   - Rename fields without preserving the original name with a '// schema-name:' comment.'
//
// If you edit this file, be careful and back it up to prevent the changes from being overridden by
// subsequent runs of the template command. Check out the PocketBase docs to find out how to use the
// generated code in your code: https://pocketbase.io/docs/go-record-proxy/
package types

import "github.com/pocketbase/pocketbase/tools/types"

type Groups struct {
	// collection-name: groups
	// system: id
	Id          string
	name        string
	description string
	managers    []*Users
	members     []*Users
	ranges      []*Ranges
	createdAt   types.DateTime
	updatedAt   types.DateTime
}

type Logs struct {
	// collection-name: logs
	// system: id
	Id       string
	user     *Users
	range_   *Ranges
	template *Templates
	// select: LogsStatusOptions(success, failure, running, aborted)[LogsStatussuccess, LogsStatusfailure, LogsStatusrunning, LogsStatusaborted]
	status  int
	start   types.DateTime
	end     types.DateTime
	log     string
	created types.DateTime
	updated types.DateTime
}

type Ranges struct {
	// collection-name: ranges
	// system: id
	Id             string
	rangeNumber    int
	rangeID        string
	name           string
	description    string
	purpose        string
	lastDeployment types.DateTime
	numberOfVMs    int
	testingEnabled bool
	allowedDomains []string
	allowedIPs     []string
	rangeState     string
	created        types.DateTime
	updated        types.DateTime
}

type Templates struct {
	// collection-name: templates
	// system: id
	Id   string
	name string
	// select: TemplatesOsOptions(linux, windows, macos, other)[TemplatesOslinux, TemplatesOswindows, TemplatesOsmacos, TemplatesOsother]
	os          int
	icon        string
	description string
	owner       *Users
	shared      bool
	created     types.DateTime
	updated     types.DateTime
}

type Users struct {
	// collection-name: users
	// system: id
	Id string
	// system: password
	password string
	// system: tokenKey
	tokenKey string
	// system: email
	email string
	// system: emailVisibility
	emailVisibility bool
	// system: verified
	verified           bool
	name               string
	avatar             string
	created            types.DateTime
	updated            types.DateTime
	userID             string
	userNumber         int
	lastActive         types.DateTime
	isAdmin            bool
	hashedAPIKey       string
	proxmoxUsername    string
	proxmoxPassword    string
	proxmoxRealm       string
	proxmoxTokenID     string
	proxmoxTokenSecret string
	quotaRAM           int
	quotaCPU           int
	quotaStorage       int
	quotaVMs           int
	quotaRanges        int
	ranges             []*Ranges
	groups             []*Groups
}

type VMs struct {
	// collection-name: vms
	// system: id
	Id        string
	proxmoxID int
	range_    *Ranges
	name      string
	poweredOn bool
	ip        string
	isRouter  bool
	cpu       int // Number of CPU cores
	ram       int // RAM in GB
	created   types.DateTime
	updated   types.DateTime
}
