- name: Install Powershell AD Tools
  ansible.windows.win_feature:
    name:
      - RSAT-AD-PowerShell
      - RSAT-AD-AdminCenter
    state: present

- name: Install Active Directory
  ansible.windows.win_feature:
    name: AD-Domain-Services
    include_management_tools: true
    include_sub_features: true
    state: present

- name: Disable password policy
  community.windows.win_security_policy:
    section: System Access
    key: PasswordComplexity
    value: 0

- name: Set DNS
  ansible.windows.win_dns_client:
    adapter_names: '*'
    dns_servers:
      - 127.0.0.1
      - "{{ dc_ip }}"

# windows_domain errors out on subsequent domain creation
# The specified argument 'CreateDNSDelegation' was not recognized
# https://github.com/ansible-collections/ansible.windows/issues/252
- name: Create domain
  microsoft.ad.domain:
    create_dns_delegation: false
    dns_domain_name: "{{ netbios_name }}.{{ fqdn_tail }}"
    domain_netbios_name: "{{ netbios_name }}"
    domain_mode: "{{ defaults.ad_domain_functional_level }}"
    forest_mode: "{{ defaults.ad_forest_functional_level }}"
    safe_mode_password: "{{ defaults.ad_domain_safe_mode_password }}"
    install_dns: true
  register: domain_creation
  failed_when:
    - domain_creation.failed
    - "domain_creation.msg is defined and \"The specified argument 'CreateDNSDelegation' was not recognized\" not in domain_creation.msg"

- name: Reboot After Domain Creation
  ansible.windows.win_reboot:
    msg: "Installing AD. Rebooting..."
    pre_reboot_delay: 15
    reboot_timeout: 600
    post_reboot_delay: 60
  when: domain_creation is changed

- name: Configure default OUs
  microsoft.ad.ou:
    name: "{{ item }}"
    path: "DC={{ netbios_name }},DC={{ fqdn_tail.split('.') | join(',DC=') }}"
    state: present
  with_items:
    - Workstations
    - Servers

# Add the router as the DNS forwarder to allow windows machines to resolve addresses
# Add home.arpa to the SuffixSearchList so we can access things by bare hostname (these will get forwarded to the router)
- name: Configure DNS forwarding
  ansible.windows.win_powershell:
    script: |
      $dnsip = "{{ dns_server }}"
      $newDNSServers = "127.0.0.1", "$dnsip"
      Add-DnsServerForwarder -IPAddress $dnsip
      Set-DnsClientGlobalSetting -SuffixSearchList @( "{{ netbios_name }}.{{ fqdn_tail }}", "home.arpa")
      Restart-Service DNS

- name: Configure DC with raw Commands
  ansible.windows.win_shell: "{{ item }}"
  with_items:
    - "wevtutil el | Select-String -notmatch \"Microsoft-Windows-LiveId\" | Foreach-Object {wevtutil cl \"$_\"}"
    - "Set-SmbServerConfiguration -AuditSmb1Access $true -Force"

- name: Disable Telemetry
  ansible.windows.win_shell: ".\\disable-telemetry.ps1"
  args:
    chdir: 'c:\ludus\scripts'
  register: disable_telemetry

- name: Disable password complexity
  community.windows.win_security_policy:
    section: System Access
    key: PasswordComplexity
    value: 0

# Well known SID
# https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/understand-security-identifiers
#
#   Domain Admins                     :     {{ domain_sid }}-512
#   Remote Desktop Users              :     S-1-5-32-555
#   Enterprise Admins                 :     {{ domain_sid }}-519
#   Schema Admins                     :     {{ domain_sid }}-518
#   Group Policy Creator Owners       :     {{ domain_sid }}-520
#
- name: Gather Domain Admins group name multilingual
  ansible.windows.win_shell: |
    (Gwmi win32_group -Filter "Domain='{{ domain_name }}' and SID='{{ domain_sid }}-512'").Name
  register: domain_admins_group_name
  when: domain_check

- debug: var=domain_admins_group_name

- name: Gather Remote Desktop Users group name multilingual
  ansible.windows.win_shell: |
    (Gwmi win32_group -Filter "SID='S-1-5-32-555'").Name
  register: rdp_users_group_name
  when: domain_check

- debug: var=rdp_users_group_name

- name: Gather Enterprise Admins group name multilingual
  ansible.windows.win_shell: |
    (Gwmi win32_group -Filter "Domain='{{ domain_name }}' and SID='{{ domain_sid }}-519'").Name
  register: enterprise_admins_group_name
  when: domain_check

- debug: var=enterprise_admins_group_name

- name: Gather Schema Admins group name multilingual
  ansible.windows.win_shell: |
    (Gwmi win32_group -Filter "Domain='{{ domain_name }}' and SID='{{ domain_sid }}-518'").Name
  register: schema_admins_group_name
  when: domain_check

- debug: var=schema_admins_group_name

- name: Gather Group Policy Creator Owners group name multilingual
  ansible.windows.win_shell: |
    (Gwmi win32_group -Filter "Domain='{{ domain_name }}' and SID='{{ domain_sid }}-520'").Name
  register: gpo_creators_group_name
  when: domain_check

- debug: var=gpo_creators_group_name

- name: Create a domain user
  microsoft.ad.user:
    name: "{{ defaults.ad_domain_user }}"
    firstname: Domain
    surname: User
    password: "{{ defaults.ad_domain_user_password }}"
    state: present
    password_never_expires: true
    groups:
      add:
        - "{{ (rdp_users_group_name.stdout|split('\n'))[0]|trim }}"  # Remote Desktop Users

- name: Create a Domain Admin user
  microsoft.ad.user:
    name: "{{ defaults.ad_domain_admin }}"
    firstname: Domain
    surname: Admin
    password: "{{ defaults.ad_domain_admin_password }}"
    state: present
    password_never_expires: true
    groups:
      add:
        - "{{ (domain_admins_group_name.stdout|split('\n'))[0]|trim }}"       # Domain Admins
        - "{{ (rdp_users_group_name.stdout|split('\n'))[0]|trim }}"           # Remote Desktop Users
        - "{{ (enterprise_admins_group_name.stdout|split('\n'))[0]|trim }}"   # Enterprise Admins
        - "{{ (schema_admins_group_name.stdout|split('\n'))[0]|trim }}"       # Schema Admins
        - "{{ (gpo_creators_group_name.stdout|split('\n'))[0]|trim }}"        # Group Policy Creator Owners

- name: Allow the domain user and domain admin to RDP
  ansible.windows.win_user_right:
    name: SeRemoteInteractiveLogonRight
    users:
      - "{{ netbios_name }}\\{{ defaults.ad_domain_user }}"
      - "{{ netbios_name }}\\{{ defaults.ad_domain_admin }}"
    action: add
