- name: Check if files have been copied
  ansible.windows.win_stat:
    path: C:\ludus\scripts
  register: file_check

- name: Create C:\ludus directory
  ansible.windows.win_file:
    path: C:\ludus
    state: directory
  when: not file_check.stat.exists

- name: Copy windows scripts to host
  ansible.windows.win_copy:
    src: windows/scripts/
    dest: C:\ludus\scripts

- name: Copy windows resources to host
  ansible.windows.win_copy:
    src: windows/background/
    dest: C:\ludus\background
  when: not file_check.stat.exists

- name: Eject any isos
  ansible.windows.win_powershell:
    script: |
      $sh = New-Object -ComObject "Shell.Application"
      $sh.Namespace(17).Items() | Where-Object { $_.Type -eq "CD Drive" } | foreach { $_.InvokeVerb("Eject") }

- name: Check if the Windows evaluation is expiring/expired
  ansible.builtin.include_tasks:
    file: rearm.yml

# See https://github.com/PowerShell/PowerShell/issues/2138 for more info
- name: Disable the Invoke-WebRequest download progress bar globally for speed improvements
  ansible.windows.win_powershell:
    script: |
      New-Item -Path $ProfilePath | Out-Null
      If (!(Get-Content $Profilepath| % { $_ -match "SilentlyContinue" } )) {
        Add-Content -Path $ProfilePath -Value "$ProgressPreference = 'SilentlyContinue'"
      }

# https://support.microsoft.com/en-gb/help/929852/guidance-for-configuring-ipv6-in-windows-for-advanced-users
# - name: Disable IPv6 for all interfaces
#   ansible.windows.win_powershell:
#     script: |
#       Get-NetAdapterBinding -ComponentID ms_tcpip6 | ForEach-Object {Disable-NetAdapterBinding -Name $_.Name -ComponentID ms_tcpip6}
#       reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters" /v DisabledComponents /t REG_DWORD /d 255 /f

- name: Check if machine is domain joined
  ansible.windows.win_shell: |
    (Get-WmiObject -Class Win32_ComputerSystem).PartOfDomain
  register: domain_check
  when: dns_server is defined

- name: Set DNS skip_dns_change fact
  ansible.builtin.set_fact:
    skip_dns_change: "{{ domain_check.stdout | trim == 'True' }}"
  when: dns_server is defined

# We only set the DNS server is not domain joined as things like GOAD set up domains outside of Ludus
- name: Set DNS (Windows) if not domain joined
  ansible.windows.win_dns_client:
    adapter_names: '*'
    dns_servers:
      - "{{ dns_server }}"
  when: dns_server is defined and not skip_dns_change

- name: Get bginfo.exe if needed
  run_once: true
  block:
    - name: "Create {{ ludus_install_path }}/resources/windows directory if it doesn't exist"
      ansible.builtin.file:
        path: "{{ ludus_install_path }}/resources/windows"
        state: directory
        recurse: true
      delegate_to: localhost

    - name: Check if bginfo.exe exists
      ansible.builtin.stat:
        path: "{{ ludus_install_path }}/resources/windows/bginfo.exe"
      delegate_to: localhost
      register: bginfo_exists

    - name: Download bginfo.exe
      ansible.builtin.get_url:
        url: https://live.sysinternals.com/bginfo.exe
        dest: "{{ ludus_install_path }}/resources/windows/bginfo.exe"
      delegate_to: localhost
      when: not bginfo_exists.stat.exists

- name: Check if bginfo.exe exists
  ansible.windows.win_stat:
    path: C:\ludus\background\bginfo.exe
  register: bginfo_stat

- name: Create C:\ludus\background directory
  ansible.windows.win_file:
    path: C:\ludus\background
    state: directory
    recursive: true
  when: not bginfo_stat.stat.exists

- name: Copy bginfo.exe to windows host
  ansible.windows.win_copy:
    src: "{{ ludus_install_path }}/resources/windows/bginfo.exe"
    dest: C:\ludus\background\bginfo.exe
  when: not bginfo_stat.stat.exists

- name: Check Run key for background script
  ansible.windows.win_reg_stat:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
    name: bginfo
  register: bginfo_run_key_stat

- name: Install bginfo Run key (if key does not exist)
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
    name: bginfo
    data: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -NonInteractive -File "C:\ludus\background\set-bg.ps1"'
    state: present
  when: not bginfo_run_key_stat.exists and defaults.enable_dynamic_wallpaper

- name: Set desktop wallpaper settings (if key does not exist)
  ansible.windows.win_regedit:
    path: HKCU:\Control Panel\Desktop
    name: TileWallpaper
    data: '0'
    state: present
  when: not bginfo_run_key_stat.exists and defaults.enable_dynamic_wallpaper

- name: Set desktop wallpaper style (if key does not exist)
  ansible.windows.win_regedit:
    path: HKCU:\Control Panel\Desktop
    name: WallpaperStyle
    data: '10'
    state: present
  when: not bginfo_run_key_stat.exists and defaults.enable_dynamic_wallpaper

- name: Disable Telemetry
  ansible.windows.win_shell: ".\\disable-telemetry.ps1"
  args:
    chdir: 'c:\ludus\scripts'
  register: disable_telemetry
