- name: Install Powershell AD Tools
  ansible.windows.win_feature:
    name:
      - RSAT-AD-PowerShell
      - RSAT-AD-AdminCenter
    state: present

- name: Install Active Directory
  ansible.windows.win_feature:
    name: AD-Domain-Services
    include_management_tools: true
    include_sub_features: true
    state: present

- name: Disable password policy
  community.windows.win_security_policy:
    section: System Access
    key: PasswordComplexity
    value: 0

- name: Set DNS
  ansible.windows.win_dns_client:
    adapter_names: '*'
    dns_servers:
      - 127.0.0.1
      - "{{ dc_ip }}"

# windows_domain errors out on subsequent domain creation
# The specified argument 'CreateDNSDelegation' was not recognized
# https://github.com/ansible-collections/ansible.windows/issues/252
- name: Create domain
  microsoft.ad.domain:
    create_dns_delegation: false
    dns_domain_name: "{{ netbios_name }}.{{ fqdn_tail }}"
    domain_netbios_name: "{{ netbios_name }}"
    domain_mode: "{{ defaults.ad_domain_functional_level }}"
    forest_mode: "{{ defaults.ad_forest_functional_level }}"
    safe_mode_password: "{{ defaults.ad_domain_safe_mode_password }}"
    install_dns: true
  register: domain_creation
  failed_when:
    - domain_creation.failed
    - "domain_creation.msg is defined and \"The specified argument 'CreateDNSDelegation' was not recognized\" not in domain_creation.msg"

- name: Reboot After Domain Creation
  ansible.windows.win_reboot:
    msg: "Installing AD. Rebooting..."
    pre_reboot_delay: 15
    reboot_timeout: 600
    post_reboot_delay: 60
  when: domain_creation is changed

- name: Configure default OUs
  microsoft.ad.ou:
    name: "{{ item }}"
    path: "DC={{ netbios_name }},DC={{ fqdn_tail.split('.') | join(',DC=') }}"
    state: present
  with_items:
    - Workstations
    - Servers

# Add the router as the DNS forwarder to allow windows machines to resolve addresses
# Add home.arpa to the SuffixSearchList so we can access things by bare hostname (these will get forwarded to the router)
- name: Configure DNS forwarding
  ansible.windows.win_powershell:
    script: |
      $dnsip = "{{ primary_dns_server }}"
      $newDNSServers = "127.0.0.1", "$dnsip"
      Add-DnsServerForwarder -IPAddress $dnsip
      Set-DnsClientGlobalSetting -SuffixSearchList @( "{{ netbios_name }}.{{ fqdn_tail }}", "home.arpa")
      Restart-Service DNS

- name: Configure DC with raw Commands
  ansible.windows.win_shell: "{{ item }}"
  with_items:
    - "wevtutil el | Select-String -notmatch \"Microsoft-Windows-LiveId\" | Foreach-Object {wevtutil cl \"$_\"}"
    - "Set-SmbServerConfiguration -AuditSmb1Access $true -Force"

- name: Disable password complexity
  community.windows.win_security_policy:
    section: System Access
    key: PasswordComplexity
    value: 0

# Well known SIDs
# https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/understand-security-identifiers
#
#   Domain Admins                     :     {{ domain_sid }}-512
#   Remote Desktop Users              :     S-1-5-32-555
#   Enterprise Admins                 :     {{ domain_sid }}-519
#   Schema Admins                     :     {{ domain_sid }}-518
#   Group Policy Creator Owners       :     {{ domain_sid }}-520

- name: Get the domain SID for this domain
  ansible.windows.win_shell: |
    (Get-ADDomain).DomainSID.Value
  register: domain_sid_command

- name: Set the domain SID
  ansible.builtin.set_fact:
    domain_sid: "{{ domain_sid_command.stdout | trim }}"

- name: Debug Domain SID
  ansible.builtin.debug:
    var: domain_sid

- name: Gather Domain Admins group name by SID (multilingual)
  ansible.windows.win_shell: |
    (Get-WmiObject win32_group -Filter "Domain='{{ netbios_name }}' and SID='{{ domain_sid }}-512'").Name
  register: domain_admins_group_name_command

- name: Set the Domain Admins group name
  ansible.builtin.set_fact:
    domain_admins_group_name: "{{ domain_admins_group_name_command.stdout | trim }}"

- name: Debug Domain Admins group name
  ansible.builtin.debug:
    var: domain_admins_group_name

- name: Gather Remote Desktop Users group name (multilingual)
  ansible.windows.win_shell: |
    (Get-WmiObject win32_group -Filter "SID='S-1-5-32-555'").Name
  register: rdp_users_group_name_command

- name: Set the Remote Desktop Users group name
  ansible.builtin.set_fact:
    rdp_users_group_name: "{{ rdp_users_group_name_command.stdout | trim }}"

- name: Debug Remote Desktop Users group name
  ansible.builtin.debug:
    var: rdp_users_group_name

- name: Gather Enterprise Admins group name (multilingual)
  ansible.windows.win_shell: |
    (Get-WmiObject win32_group -Filter "Domain='{{ netbios_name }}' and SID='{{ domain_sid }}-519'").Name
  register: enterprise_admins_group_name_command

- name: Set the Enterprise Admins group name
  ansible.builtin.set_fact:
    enterprise_admins_group_name: "{{ enterprise_admins_group_name_command.stdout | trim }}"

- name: Debug Enterprise Admins group name
  ansible.builtin.debug:
    var: enterprise_admins_group_name

- name: Gather Schema Admins group name (multilingual)
  ansible.windows.win_shell: |
    (Get-WmiObject win32_group -Filter "Domain='{{ netbios_name }}' and SID='{{ domain_sid }}-518'").Name
  register: schema_admins_group_name_command

- name: Set the Schema Admins group name
  ansible.builtin.set_fact:
    schema_admins_group_name: "{{ schema_admins_group_name_command.stdout | trim }}"

- name: Debug Schema Admins group name
  ansible.builtin.debug:
    var: schema_admins_group_name

- name: Gather Group Policy Creator Owners group name (multilingual)
  ansible.windows.win_shell: |
    (Get-WmiObject win32_group -Filter "Domain='{{ netbios_name }}' and SID='{{ domain_sid }}-520'").Name
  register: gpo_creators_group_name_command

- name: Set the Group Policy Creator Owners group name
  ansible.builtin.set_fact:
    gpo_creators_group_name: "{{ gpo_creators_group_name_command.stdout | trim }}"

- name: Debug Group Policy Creator Owners group name
  ansible.builtin.debug:
    var: gpo_creators_group_name

- name: Create a domain user
  microsoft.ad.user:
    name: "{{ defaults.ad_domain_user }}"
    firstname: Domain
    surname: User
    password: "{{ defaults.ad_domain_user_password }}"
    state: present
    password_never_expires: true
    groups:
      add:
        - "{{ rdp_users_group_name }}"  # Remote Desktop Users

- name: Create a Domain Admin user
  microsoft.ad.user:
    name: "{{ defaults.ad_domain_admin }}"
    firstname: Domain
    surname: Admin
    password: "{{ defaults.ad_domain_admin_password }}"
    state: present
    password_never_expires: true
    groups:
      add:
        - "{{ domain_admins_group_name }}"       # Domain Admins
        - "{{ rdp_users_group_name }}"           # Remote Desktop Users
        - "{{ enterprise_admins_group_name }}"   # Enterprise Admins
        - "{{ schema_admins_group_name }}"       # Schema Admins
        - "{{ gpo_creators_group_name }}"        # Group Policy Creator Owners

- name: Allow the domain user and domain admin to RDP
  ansible.windows.win_user_right:
    name: SeRemoteInteractiveLogonRight
    users:
      - "{{ netbios_name }}\\{{ defaults.ad_domain_user }}"
      - "{{ netbios_name }}\\{{ defaults.ad_domain_admin }}"
    action: add

- name: Set the DNS Cache time to 2 seconds (helps DNS blocks at the router be more effective)
  ansible.windows.win_shell: |
    Set-DnsServerCache -MaxTTL 00:00:02

