---
- name: Enable default WMI allow rule
  community.windows.win_firewall_rule:
    name: Windows Management Instrumentation (WMI-In)
    action: allow
    state: present
  when:
    - firewall_service_running is defined
    - firewall_service_running
