---

# https://learn.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#minimum-version
- name: Register currently installed .NET Framework version
  block:
    - name: Register currently installed .NET Framework version
      ansible.windows.win_reg_stat:
        path: 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full'
        name: 'Release'
      register: dotnet_framework
      failed_when: dotnet_framework.value is not defined
  rescue:
    - name: Set default .NET Framework version (e.g., 0 if not found)
      ansible.builtin.set_fact:
        dotnet_framework:
          value: "0"

- name: Show dotnet_framework version
  ansible.builtin.debug:
    var: dotnet_framework.value

- name: Ensure .NET Framework 4.8 requirement is satisfied for Chocolatey CLI v2.0.0+
  when: (dotnet_framework.value | int) < 528040 # 528040 is the release number for .NET Framework 4.8 (see link above)
  block:
    - name: Install Chocolatey CLI v1.4.0
      chocolatey.chocolatey.win_chocolatey:
        name: 'chocolatey'
        state: present
        version: '1.4.0'

    - name: Install Microsoft .NET Framework 4.8
      chocolatey.chocolatey.win_chocolatey:
        name: 'netfx-4.8'
        state: present

    - name: Reboot the host to complete .NET Framework 4.8 install
      ansible.windows.win_reboot:

    - name: Install Chocolatey CLI v2.0.0+ when .NET Framework 4.8 dependency is met
      chocolatey.chocolatey.win_chocolatey:
        name: 'chocolatey'
        state: latest
