- name: Skip checking for SSH availability if the VM was just cloned
  ansible.builtin.meta: end_host
  when: (vm_name | default('')) in (cloned_vms | default([]))

- name: Wait for the host's control interface (SSH) to come up
  ansible.builtin.wait_for:
    host: "{{ target_ip }}"
    port: 22
    delay: 3
    state: started
    timeout: 900 # Router/host reboot and network rebind can take longer than the default timeout
  delegate_to: localhost
  become: false

# Required to get the new IP address into the inventory
- name: Refresh inventory
  ansible.builtin.meta: refresh_inventory
