- name: Pre run checks
  hosts: localhost
  tags: [always]
  gather_facts: false
  tasks:
    - name: Check for Proxmox token
      ansible.builtin.assert:
        that:
          - hostvars['localhost'].proxmox_full_token_id is defined
          - hostvars['localhost'].proxmox_token_secret is defined
        fail_msg: "Proxmox token is not defined"
        success_msg: "Proxmox token is defined"

    - name: Split the token id
      ansible.builtin.set_fact:
        proxmox_token_username: "{{ hostvars['localhost']['proxmox_full_token_id'] | split('!') | first }}"
        proxmox_token_id: "{{ hostvars['localhost']['proxmox_full_token_id'] | split('!') | last }}"

    - name: Check for valid token id
      ansible.builtin.assert:
        that:
          - proxmox_token_username == hostvars['localhost']['api_user']

    - name: Check for valid dynamic inventory
      ansible.builtin.assert:
        that:
          # If the user is an admin, and deploys an ADMIN VM (i.e. nexus cache) and then deletes their range, they will not have their range_id in groups.
          # https://gitlab.com/badsectorlabs/ludus/-/issues/107
          - range_id in groups or 'ADMIN' in groups
        fail_msg: "Dynamic inventory failed to load correctly. This may be an issue if the ludus-token was modified in Proxmox."
        success_msg: "Dynamic inventory loaded!"
