- name: Pre-run checks
  ansible.builtin.import_playbook: pre-run-checks.yml

- name: Validate
  tags: [always]
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Validate router host pattern will match a host
      ansible.builtin.fail:
        msg: "Target router is not up. Router host pattern '{{ router.vm_name | default(default_router_vm_name) }}' will not match any hosts. This usually means the router VM name is incorrect or the range has not been deployed yet."
      when: (router.vm_name | default(default_router_vm_name)) not in groups['all'] and (router.vm_name | default(default_router_vm_name)) not in groups['ungrouped']

- name: Apply all user defined network rules to the router
  tags: [always]
  hosts: "{{ router.vm_name | default(default_router_vm_name) }}"
  become: true
  tasks:
    - name: Set any user defined firewall rules
      ansible.builtin.include_tasks: tasks/firewall/set-firewall-rules.yml
