---
- name: Setup Kali (install kasmvnc)
  hosts: all
  become_method: sudo
  tasks:
    # See: https://bugs.kali.org/view.php?id=9027
    - name: Install from python-apt from source if needed
      become: true
      ansible.builtin.shell:
        cmd: |
          apt update 2>&1 | grep 'undefined symbol: _ZNS' >/dev/null && \
            echo "Python-apt bug found, fixing from source..." >> /tmp/kali-install.log && \
            DEBIAN_FRONTEND=noninteractive apt install -y python3-setuptools dpkg-dev python3-dev libapt-pkg-dev >> /tmp/kali-install.log 2>&1 && \
            git clone https://salsa.debian.org/apt-team/python-apt >> /tmp/kali-install.log 2>&1 && cd python-apt && \
            git checkout 2.9.2 >> /tmp/kali-install.log 2>&1 && \
            python3 setup.py build >> /tmp/kali-install.log 2>&1 && \
            python3 setup.py install >> /tmp/kali-install.log 2>&1 || \
          echo "No python-apt bug found" >> /tmp/kali-install.log

    - name: Try an apt install
      become: true
      ansible.builtin.apt:
        name:
          - git
        state: present
        update_cache: true
      register: apt_result
      ignore_errors: true

    # This is a fix for the "python3-apt must be installed and visible from /usr/bin/python3" error in Kali 2024.4
    - name: Fix apt for ansible if needed
      become: true
      ansible.builtin.shell:
        cmd: |
          echo "Python-apt bug 2 found, fixing from source..." >> /tmp/kali-install.log && \
          DEBIAN_FRONTEND=noninteractive apt install -y python3-setuptools dpkg-dev python3-dev libapt-pkg-dev >> /tmp/kali-install.log 2>&1 && \
          git clone https://salsa.debian.org/apt-team/python-apt >> /tmp/kali-install.log 2>&1 && cd python-apt && \
          git checkout 2.9.6 >> /tmp/kali-install.log 2>&1 && \
          python3 setup.py build >> /tmp/kali-install.log 2>&1 && \
          python3 setup.py install >> /tmp/kali-install.log 2>&1
      when: apt_result.failed

    - name: Install packages
      become: true
      ansible.builtin.apt:
        name:
          - git
          - python3-pip
          - jq
          - curl
          - dbus
          - dbus-user-session
          - dbus-x11
          - vim
          - swapspace # helps with machines with low RAM
          - kali-defaults
          - kali-root-login
          - desktop-base
          - wget
          - kali-linux-core
          - kali-desktop-xfce
          # - kali-linux-default # This takes forever (2+ hours) and really slows down template building
        state: present
      register: result
      retries: 2
      until: result.failed == false

    - name: Installing kasm dependencies
      become: true
      ansible.builtin.apt:
        autoremove: true
        state: present
        name:
          - libexporter-tiny-perl
          - libhash-merge-simple-perl
          - liblist-moreutils-perl
          - liblist-moreutils-xs-perl
          - libswitch-perl
          - libyaml-tiny-perl
          - ssl-cert

    - name: Download kasmvnc deb
      ansible.builtin.get_url:
        url: https://github.com/kasmtech/KasmVNC/releases/download/v1.3.2/kasmvncserver_kali-rolling_1.3.2_amd64.deb
        dest: /tmp/kasmvncserver_kali-rolling.deb
        mode: '0700'

    - name: Install the kasmvnc deb
      become: true
      ansible.builtin.apt:
        deb: /tmp/kasmvncserver_kali-rolling.deb
        state: present

    - name: Add Kali to the ssl-cert group
      become: true
      ansible.builtin.user:
        name: kali
        groups: ssl-cert
        append: true

    - name: Create .vnc directory for VNC user
      ansible.builtin.file:
        path: /home/kali/.vnc
        state: directory
        mode: '0755'
        owner: kali
        group: kali

    # Add a user to the vncserver, create a systemd service for it
    - name: Set the password for the kali user
      ansible.builtin.shell:
        cmd: |
          printf "password\npassword\n\n" | vncpasswd -u kali -ow /home/kali/.kasmpasswd

    - name: Set correct permissions for VNC passwd file
      ansible.builtin.file:
        path: /home/kali/.kasmpasswd
        owner: kali
        group: kali
        mode: '0600'

    - name: Set the de-was-selected file
      ansible.builtin.file:
        path: "/home/kali/.vnc/.de-was-selected"
        state: touch
        owner: kali
        group: kali
        mode: '0644'

    - name: Create xstartup script
      ansible.builtin.copy:
        dest: "/home/kali/.vnc/xstartup"
        force: false
        mode: '0755'
        content: |-
          #!/bin/bash
          exec xfce4-session

    - name: Deploy kasmvnc.yml config to user ~/.vnc
      ansible.builtin.blockinfile:
        path: "/home/kali/.vnc/kasmvnc.yaml"
        create: true
        block: |
          desktop:
            resolution:
              width: 1920
              height: 1080
            allow_resize: true
            pixel_depth: 24

          keyboard:
            remap_keys:
            ignore_numlock: false
            raw_keyboard: true

          user_session:
            idle_timeout: never

          server:
            auto_shutdown:
              no_user_session_timeout: never
              active_user_session_timeout: never
              inactive_user_session_timeout: never

          pointer:
            enabled: true

    - name: Create a service for kasmvnc
      become: true
      ansible.builtin.blockinfile:
        path: /etc/systemd/system/kasmvnc@1.service
        create: true
        block: |
          [Unit]
          Description=Remote desktop service (VNC)
          After=syslog.target network.target
          StartLimitIntervalSec=30s
          StartLimitBurst=5

          [Service]
          Type=simple
          User=kali
          PIDFile=/home/kali/.vnc/%H%i.pid
          ExecStartPre=/bin/sh -c "/usr/bin/kasmvncserver -kill :%i > /dev/null 2>&1 || :"
          ExecStart=/usr/bin/kasmvncserver :%i -localhost no -alwaysshared -fg -geometry 1920x1080 -SecurityTypes VncAuth -PublicIP 127.0.0.1
          ExecStop=/usr/bin/kasmvncserver -kill :%i
          Restart=on-failure
          RestartSec=5s

          [Install]
          WantedBy=multi-user.target

    - name: Enable the kasmvnc service
      become: true
      ansible.builtin.service:
        name: kasmvnc@1.service
        enabled: true
        daemon_reload: true
