- name: Ensure Blocky is installed
  ansible.builtin.include_tasks: tasks/router/ensure-blocky.yml

- name: Load Blocky DNS state
  ansible.builtin.include_tasks: tasks/router/load-blocky-state.yml

- name: Initialize range DNS rewrites
  ansible.builtin.set_fact:
    blocky_range_rewrites: {}

- name: Build range DNS rewrites
  ansible.builtin.set_fact:
    blocky_range_rewrites: >-
      {{
        blocky_range_rewrites | combine({
          (item.hostname | lower | regex_replace('^.*?-', '')): '10.' + (range_second_octet | string) + '.' + (item.vlan | string) + '.' + (item.ip_last_octet | string),
          (item.hostname | lower): '10.' + (range_second_octet | string) + '.' + (item.vlan | string) + '.' + (item.ip_last_octet | string),
          ((item.hostname | lower | regex_replace('^.*?-', '')) + '.home.arpa'): '10.' + (range_second_octet | string) + '.' + (item.vlan | string) + '.' + (item.ip_last_octet | string),
          ((item.hostname | lower) + '.home.arpa'): '10.' + (range_second_octet | string) + '.' + (item.vlan | string) + '.' + (item.ip_last_octet | string)
        })
      }}
  loop: "{{ ludus }}"

- name: Reset range and user DNS rewrite state
  ansible.builtin.set_fact:
    blocky_state: "{{ blocky_state | combine({'range_rewrites': blocky_range_rewrites, 'user_rewrites': {}, 'wildcard_rewrites': {}}, recursive=True) }}"

- name: Save Blocky DNS state
  ansible.builtin.include_tasks: tasks/router/save-blocky-state.yml
