- name: Setup ip forwarding on the router
  become: true
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: true
    state: present
    reload: true

- name: Disable ipv6
  become: true
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: 1
    sysctl_set: true
    state: present
    reload: true

- name: Install dnsmasq, ca-certificates, and iptables-persistent
  ansible.builtin.apt:
    name:
      - dnsmasq
      - iptables-persistent
      - ca-certificates
      - rsync
      - curl
      - conntrack
      - tar
    state: present

- name: Disable DNS in dnsmasq (only use it for DHCP)
  ansible.builtin.lineinfile:
    path: /etc/dnsmasq.conf
    line: 'port=0'
    create: true

- name: Restart dnsmasq service to pick up changes
  ansible.builtin.service:
    name: dnsmasq
    state: restarted

- name: Install Blocky
  ansible.builtin.include_tasks: tasks/router/ensure-blocky.yml

- name: Load Blocky DNS state
  ansible.builtin.include_tasks: tasks/router/load-blocky-state.yml

- name: Save initial Blocky DNS state
  ansible.builtin.include_tasks: tasks/router/save-blocky-state.yml

- name: Drop a file to signal that we have completed configuration
  ansible.builtin.file:
    path: /etc/.ludus-configured
    state: touch
