# As suggested by https://docs.ansible.com/ansible/latest/os_guide/windows_performance.html#fix-high-cpu-on-boot-for-vms-cloud-instances

- name: Generate native .NET images for CPU
  hosts: all
  tasks:
    - name: Run ngen tasks
      community.windows.win_dotnet_ngen:
