# proxmox_kvm options
api_user: "{{ lookup('env', 'PROXMOX_USERNAME') }}"
api_host: "{{ lookup('env', 'PROXMOX_HOSTNAME') | default('127.0.0.1') }}"
proxmox_full_token_id: "{{ lookup('env', 'PROXMOX_TOKEN') }}"
proxmox_token_secret: "{{ lookup('env', 'PROXMOX_SECRET') }}"
node_name: "{{ lookup('env', 'PROXMOX_NODE') }}"
proxmox_default_behavior: compatibility
ansible_remote_tmp: "{{ '/opt/ludus/ansible/tmp' if (lookup('env', 'USER') != 'root') else '/tmp/.ansible/tmp' }}"
