Suite: trixie
CacheDir: ../cache
Source: http://deb.debian.org/debian SUITE main contrib
Source: http://deb.debian.org/debian SUITE-updates main contrib
Source: http://security.debian.org/debian-security SUITE-security main contrib
Architecture: amd64
Name: ludus
Version: __LUDUS_VERSION__
Section: system
Maintainer: Bad Sector Labs <ludus@badsectorlabs.com>
Infopage: https://ludus.cloud
Description: Ludus cyber range server (LXC appliance)
