package main

import (
	"fmt"
	"log"
	"os"

	"gopkg.in/yaml.v2"
)

// check the configuration file to ensure it exists and that it does not have default values
func checkConfig() {
	configPath := fmt.Sprintf("%s/config.yml", ludusPath)

	if !fileExists(configPath) {
		log.Fatalf("Config file (%s) missing! config.yml is generated by install.sh and pushed into the LXC; set up %s/config.yml manually or run install.sh on the Proxmox host.", configPath, ludusInstallPath)
	}

	// Open config file
	file, err := os.Open(configPath)
	if err != nil {
		log.Fatalf("Error opening config: %v", err)
	}
	defer file.Close()

	// Init new YAML decode
	d := yaml.NewDecoder(file)

	// Start YAML decoding from file
	if err := d.Decode(&config); err != nil {
		log.Fatalf("Error decoding config: %v", err)
	}

	config.ApplyDefaults()
	if err := config.ApplyShimAndValidate(); err != nil {
		log.Fatalf("config validation: %v", err)
	}
	if err := config.ApplyPortDefaultsAndValidate(); err != nil {
		log.Fatalf("%v", err)
	}
}

// check if the current uid is zero (root) and throw a fatal error if not
func checkRoot() {
	if os.Geteuid() != 0 {
		log.Fatal("Ludus must be run as root.")
	}
}
