package main

import (
	"fmt"
	"log"
	"os"

	"gopkg.in/yaml.v2"
)

func generateConfigIfAutomatedInstall() {
	configPath := fmt.Sprintf("%s/config.yml", ludusPath)
	// First run, no config
	if ludusPath != fmt.Sprintf("%s/ludus-server", ludusInstallPath) && !fileExists(configPath) {
		// If we are running without prompts, generate a config automatically
		if autoGenerateConfig {
			log.Fatalf("auto-config generation removed: config.yml is generated by install.sh and pushed into the LXC. Set up %s/config.yml manually or run install.sh on the Proxmox host.", ludusInstallPath)
		}
	}
}

// check the configuration file to ensure it exists and that it does not have default values
func checkConfig() {
	configPath := fmt.Sprintf("%s/config.yml", ludusPath)

	if ludusPath == fmt.Sprintf("%s/ludus-server", ludusInstallPath) && !fileExists(configPath) { // Installed, but config missing
		log.Printf("Config file (%s) missing!\n", configPath)
		os.Exit(1)
	}

	// Open config file
	file, err := os.Open(configPath)
	if err != nil {
		log.Fatalf("Error opening config: %v", err)
	}
	defer file.Close()

	// Init new YAML decode
	d := yaml.NewDecoder(file)

	// Start YAML decoding from file
	if err := d.Decode(&config); err != nil {
		log.Fatalf("Error decoding config: %v", err)
	}

	if err := config.ApplyPortDefaultsAndValidate(); err != nil {
		log.Fatalf("%v", err)
	}
}

// check if the current uid is zero (root) and throw a fatal error if not
func checkRoot() {
	if os.Geteuid() != 0 {
		log.Fatal("Ludus must be run as root.")
	}
}
