package main

import (
	"fmt"
	"log"
	ludusapi "ludusapi"
	"os"

	"gopkg.in/yaml.v2"
)

// automatedConfigGenerator previously probed the Proxmox host (pveversion, pvesh,
// net.Interfaces, ip route) to synthesize a config.yml on first run. The server
// now runs inside an LXC and cannot reach those host facilities; install.sh on
// the Proxmox host is responsible for generating config.yml and pushing it into
// the container. Any code path that still reaches this function is a bug.
func automatedConfigGenerator(writeToFile bool) {
	_ = writeToFile
	log.Fatalf("auto-config generation removed: config.yml is generated by install.sh and pushed into the LXC. Set up %s/config.yml manually or run install.sh on the Proxmox host.", ludusInstallPath)
}

// Load the config file from disk into the config struct
func loadConfig() {
	// Read the config file
	data, err := os.ReadFile(fmt.Sprintf("%s/config.yml", ludusInstallPath))
	if err != nil {
		log.Fatalf("Error opening config: %v", err)
	}
	err = yaml.Unmarshal(data, &config)
	if err != nil {
		log.Fatalf("Error unmarshalling config: %v", err)
	}
	if err := config.ApplyPortDefaultsAndValidate(); err != nil {
		log.Fatalf("%v", err)
	}
}

func writeConfigToFile(config ludusapi.Configuration, filename string) error {
	// Marshal the struct to YAML
	data, err := yaml.Marshal(&config)
	if err != nil {
		return fmt.Errorf("error marshaling YAML: %v", err)
	}

	// Write the YAML to a file
	err = os.WriteFile(filename, data, 0644)
	if err != nil {
		return fmt.Errorf("error writing file: %v", err)
	}

	return nil
}
