package ludusapi

import (
	"archive/zip"
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"ludusapi/pluginrpc"
)

const pluginUploadLimit = 128 << 20
const pluginUILimit = 2 << 20

var pluginIDPattern = regexp.MustCompile(`^[a-z][a-z0-9-]{1,63}$`)

// A package is a ZIP with an inert manifest, optional plugin executable, and
// optional self-contained HTML document. Reading a package never executes code.
type PluginManifest struct {
	SchemaVersion int    `json:"schemaVersion"`
	ID            string `json:"id"`
	Name          string `json:"name"`
	Version       string `json:"version"`
	Description   string `json:"description"`
	Author        string `json:"author"`
	Executable    string `json:"executable,omitempty"`
	UI            string `json:"ui,omitempty"`
	RangeScoped   bool   `json:"rangeScoped"`
	Protocol      int    `json:"protocolVersion,omitempty"`
}

type pluginPackage struct {
	manifest PluginManifest
	files    map[string][]byte
	digest   string
}

func readPluginPackage(data []byte) (*pluginPackage, error) {
	if len(data) > pluginUploadLimit {
		return nil, fmt.Errorf("plugin package exceeds 128 MiB")
	}
	z, err := zip.NewReader(bytes.NewReader(data), int64(len(data)))
	if err != nil {
		return nil, fmt.Errorf("expected a ZIP plugin package: %w", err)
	}
	if len(z.File) > 3 {
		return nil, fmt.Errorf("package must contain only plugin.json, plugin, and ui/index.html")
	}
	result := &pluginPackage{files: make(map[string][]byte)}
	for _, f := range z.File {
		limit := int64(pluginUploadLimit)
		switch f.Name {
		case "plugin.json":
			limit = 65536
		case "plugin":
		case "ui/index.html":
			limit = pluginUILimit
		default:
			return nil, fmt.Errorf("unsupported package entry %q", f.Name)
		}
		if _, exists := result.files[f.Name]; exists {
			return nil, fmt.Errorf("duplicate package entry %q", f.Name)
		}
		if !f.Mode().IsRegular() || f.Mode()&os.ModeSymlink != 0 || f.UncompressedSize64 > uint64(limit) {
			return nil, fmt.Errorf("invalid or oversized package entry %q", f.Name)
		}
		r, err := f.Open()
		if err != nil {
			return nil, err
		}
		body, err := io.ReadAll(io.LimitReader(r, limit+1))
		r.Close()
		if err != nil {
			return nil, err
		}
		if int64(len(body)) > limit {
			return nil, fmt.Errorf("oversized package entry %q", f.Name)
		}
		result.files[f.Name] = body
	}
	decoder := json.NewDecoder(bytes.NewReader(result.files["plugin.json"]))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&result.manifest); err != nil {
		return nil, fmt.Errorf("invalid plugin.json: %w", err)
	}
	if err := decoder.Decode(new(any)); err != io.EOF {
		return nil, fmt.Errorf("unexpected trailing manifest data")
	}
	m := result.manifest
	if m.SchemaVersion != 1 || !pluginIDPattern.MatchString(m.ID) || strings.TrimSpace(m.Name) == "" || strings.TrimSpace(m.Version) == "" || len(m.Name) > 120 || len(m.Version) > 64 || len(m.Description) > 2000 || len(m.Author) > 200 {
		return nil, fmt.Errorf("invalid plugin manifest identity or schema version")
	}
	if m.Executable != "" && (m.Executable != "plugin" || m.Protocol != pluginrpc.ProtocolVersion) {
		return nil, fmt.Errorf("executable must be plugin and protocolVersion must be %d", pluginrpc.ProtocolVersion)
	}
	if m.UI != "" && m.UI != "ui/index.html" {
		return nil, fmt.Errorf("ui must be ui/index.html")
	}
	if m.UI == "" && m.Executable == "" {
		return nil, fmt.Errorf("package needs an executable or UI")
	}
	for _, name := range []string{m.Executable, m.UI} {
		if name != "" && len(result.files[name]) == 0 {
			return nil, fmt.Errorf("missing %s", name)
		}
	}
	if (m.UI == "" && result.files["ui/index.html"] != nil) || (m.Executable == "" && result.files["plugin"] != nil) {
		return nil, fmt.Errorf("undeclared package entry")
	}
	sum := sha256.Sum256(data)
	result.digest = hex.EncodeToString(sum[:])
	return result, nil
}

func storePluginPackage(root, id string, pkg *pluginPackage) error {
	// Record IDs are generated by PocketBase, never supplied as filesystem paths.
	if !regexp.MustCompile(`^[a-zA-Z0-9]{15}$`).MatchString(id) {
		return fmt.Errorf("invalid package record ID")
	}
	if err := os.MkdirAll(root, 0700); err != nil {
		return err
	}
	tmp, err := os.MkdirTemp(root, ".staging-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmp)
	for name, body := range pkg.files {
		destination := filepath.Join(tmp, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(destination), 0700); err != nil {
			return err
		}
		// The executable stays non-executable until its manager activates it.
		if err := os.WriteFile(destination, body, 0600); err != nil {
			return err
		}
	}
	return os.Rename(tmp, filepath.Join(root, id))
}
