name: ludus-gui

services:
  ludus-gui:
    image: registry.badsectorlabs.com/ludus-gui:beta-latest
    environment:
      - LUDUS_API_BASE_URL=https://198.51.100.1:8080
      - NEXT_PUBLIC_SUPABASE_URL=https://192.0.2.1
      - NEXT_PUBLIC_SUPABASE_ANON_KEY={{ supabase_anon_key }}

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
