// Autogenerated by github.com/snonky/pocketbase-gogen. Do not edit.

// Must edit these:

/*
func (p *Ranges) AllowedDomains() []string {
	return p.GetStringSlice("allowedDomains")
}

func (p *Ranges) SetAllowedDomains(allowedDomains []string) {
	p.Set("allowedDomains", allowedDomains)
}

func (p *Ranges) AllowedIps() []string {
	return p.GetStringSlice("allowedIPs")
}

func (p *Ranges) SetAllowedIps(allowedIps []string) {
	p.Set("allowedIPs", allowedIps)
}
*/

package models

import (
	"github.com/pocketbase/pocketbase/core"
	"github.com/pocketbase/pocketbase/tools/types"
)

type Groups struct {
	core.BaseRecordProxy
}

func (p *Groups) CollectionName() string {
	return "groups"
}

func (p *Groups) Name() string {
	return p.GetString("name")
}

func (p *Groups) SetName(name string) {
	p.Set("name", name)
}

func (p *Groups) Description() string {
	return p.GetString("description")
}

func (p *Groups) SetDescription(description string) {
	p.Set("description", description)
}

func (p *Groups) Managers() []*Users {
	rels := p.ExpandedAll("managers")
	proxies := make([]*Users, len(rels))
	for i := range len(rels) {
		proxies[i] = &Users{}
		proxies[i].Record = rels[i]
	}
	return proxies
}

func (p *Groups) SetManagers(managers []*Users) {
	records := make([]*core.Record, len(managers))
	ids := make([]string, len(managers))
	for i, r := range managers {
		records[i] = r.Record
		ids[i] = r.Record.Id
	}
	p.Record.Set("managers", ids)
	e := p.Expand()
	e["managers"] = records
	p.SetExpand(e)
}

func (p *Groups) Members() []*Users {
	rels := p.ExpandedAll("members")
	proxies := make([]*Users, len(rels))
	for i := range len(rels) {
		proxies[i] = &Users{}
		proxies[i].Record = rels[i]
	}
	return proxies
}

func (p *Groups) SetMembers(members []*Users) {
	records := make([]*core.Record, len(members))
	ids := make([]string, len(members))
	for i, r := range members {
		records[i] = r.Record
		ids[i] = r.Record.Id
	}
	p.Record.Set("members", ids)
	e := p.Expand()
	e["members"] = records
	p.SetExpand(e)
}

func (p *Groups) Ranges() []*Ranges {
	rels := p.ExpandedAll("ranges")
	proxies := make([]*Ranges, len(rels))
	for i := range len(rels) {
		proxies[i] = &Ranges{}
		proxies[i].Record = rels[i]
	}
	return proxies
}

func (p *Groups) SetRanges(ranges []*Ranges) {
	records := make([]*core.Record, len(ranges))
	ids := make([]string, len(ranges))
	for i, r := range ranges {
		records[i] = r.Record
		ids[i] = r.Record.Id
	}
	p.Record.Set("ranges", ids)
	e := p.Expand()
	e["ranges"] = records
	p.SetExpand(e)
}

func (p *Groups) CreatedAt() types.DateTime {
	return p.GetDateTime("createdAt")
}

func (p *Groups) SetCreatedAt(createdAt types.DateTime) {
	p.Set("createdAt", createdAt)
}

func (p *Groups) UpdatedAt() types.DateTime {
	return p.GetDateTime("updatedAt")
}

func (p *Groups) SetUpdatedAt(updatedAt types.DateTime) {
	p.Set("updatedAt", updatedAt)
}

type LogsStatusOptions int

const (
	LogsStatussuccess LogsStatusOptions = iota
	LogsStatusfailure
	LogsStatusrunning
	LogsStatusaborted
)

var zzLogsStatusOptionsSelectNameMap = map[string]LogsStatusOptions{
	"success": 0,
	"failure": 1,
	"running": 2,
	"aborted": 3,
}
var zzLogsStatusOptionsSelectIotaMap = map[LogsStatusOptions]string{
	0: "success",
	1: "failure",
	2: "running",
	3: "aborted",
}

type Logs struct {
	core.BaseRecordProxy
}

func (p *Logs) CollectionName() string {
	return "logs"
}

func (p *Logs) User() *Users {
	var proxy *Users
	if rel := p.ExpandedOne("user"); rel != nil {
		proxy = &Users{}
		proxy.Record = rel
	}
	return proxy
}

func (p *Logs) SetUser(user *Users) {
	var id string
	if user != nil {
		id = user.Id
	}
	p.Record.Set("user", id)
	e := p.Expand()
	if user != nil {
		e["user"] = user.Record
	} else {
		delete(e, "user")
	}
	p.SetExpand(e)
}

func (p *Logs) Range() *Ranges {
	var proxy *Ranges
	if rel := p.ExpandedOne("range"); rel != nil {
		proxy = &Ranges{}
		proxy.Record = rel
	}
	return proxy
}

func (p *Logs) SetRange(range_ *Ranges) {
	var id string
	if range_ != nil {
		id = range_.Id
	}
	p.Record.Set("range", id)
	e := p.Expand()
	if range_ != nil {
		e["range"] = range_.Record
	} else {
		delete(e, "range")
	}
	p.SetExpand(e)
}

func (p *Logs) Template() *Templates {
	var proxy *Templates
	if rel := p.ExpandedOne("template"); rel != nil {
		proxy = &Templates{}
		proxy.Record = rel
	}
	return proxy
}

func (p *Logs) SetTemplate(template *Templates) {
	var id string
	if template != nil {
		id = template.Id
	}
	p.Record.Set("template", id)
	e := p.Expand()
	if template != nil {
		e["template"] = template.Record
	} else {
		delete(e, "template")
	}
	p.SetExpand(e)
}

func (p *Logs) Status() LogsStatusOptions {
	option := p.GetString("status")
	i, ok := zzLogsStatusOptionsSelectNameMap[option]
	if !ok {
		panic("Unknown select value")
	}
	return i
}

func (p *Logs) SetStatus(status LogsStatusOptions) {
	i, ok := zzLogsStatusOptionsSelectIotaMap[status]
	if !ok {
		panic("Unknown select value")
	}
	p.Set("status", i)
}

func (p *Logs) Start() types.DateTime {
	return p.GetDateTime("start")
}

func (p *Logs) SetStart(start types.DateTime) {
	p.Set("start", start)
}

func (p *Logs) End() types.DateTime {
	return p.GetDateTime("end")
}

func (p *Logs) SetEnd(end types.DateTime) {
	p.Set("end", end)
}

func (p *Logs) Log() string {
	return p.GetString("log")
}

func (p *Logs) SetLog(log string) {
	p.Set("log", log)
}

func (p *Logs) Created() types.DateTime {
	return p.GetDateTime("created")
}

func (p *Logs) SetCreated(created types.DateTime) {
	p.Set("created", created)
}

func (p *Logs) Updated() types.DateTime {
	return p.GetDateTime("updated")
}

func (p *Logs) SetUpdated(updated types.DateTime) {
	p.Set("updated", updated)
}

type Ranges struct {
	core.BaseRecordProxy
}

func (p *Ranges) CollectionName() string {
	return "ranges"
}

func (p *Ranges) RangeNumber() int {
	return p.GetInt("rangeNumber")
}

func (p *Ranges) SetRangeNumber(rangeNumber int) {
	p.Set("rangeNumber", rangeNumber)
}

func (p *Ranges) RangeId() string {
	return p.GetString("rangeID")
}

func (p *Ranges) SetRangeId(rangeId string) {
	p.Set("rangeID", rangeId)
}

func (p *Ranges) Name() string {
	return p.GetString("name")
}

func (p *Ranges) SetName(name string) {
	p.Set("name", name)
}

func (p *Ranges) Description() string {
	return p.GetString("description")
}

func (p *Ranges) SetDescription(description string) {
	p.Set("description", description)
}

func (p *Ranges) Purpose() string {
	return p.GetString("purpose")
}

func (p *Ranges) SetPurpose(purpose string) {
	p.Set("purpose", purpose)
}

func (p *Ranges) LastDeployment() types.DateTime {
	return p.GetDateTime("lastDeployment")
}

func (p *Ranges) SetLastDeployment(lastDeployment types.DateTime) {
	p.Set("lastDeployment", lastDeployment)
}

func (p *Ranges) NumberOfVms() int {
	return p.GetInt("numberOfVMs")
}

func (p *Ranges) SetNumberOfVms(numberOfVms int) {
	p.Set("numberOfVMs", numberOfVms)
}

func (p *Ranges) TestingEnabled() bool {
	return p.GetBool("testingEnabled")
}

func (p *Ranges) SetTestingEnabled(testingEnabled bool) {
	p.Set("testingEnabled", testingEnabled)
}

func (p *Ranges) AllowedDomains() []string {
	return p.GetStringSlice("allowedDomains")
}

func (p *Ranges) SetAllowedDomains(allowedDomains []string) {
	p.Set("allowedDomains", allowedDomains)
}

func (p *Ranges) AllowedIps() []string {
	return p.GetStringSlice("allowedIPs")
}

func (p *Ranges) SetAllowedIps(allowedIps []string) {
	p.Set("allowedIPs", allowedIps)
}

func (p *Ranges) RangeState() string {
	return p.GetString("rangeState")
}

func (p *Ranges) SetRangeState(rangeState string) {
	p.Set("rangeState", rangeState)
}

func (p *Ranges) Created() types.DateTime {
	return p.GetDateTime("created")
}

func (p *Ranges) SetCreated(created types.DateTime) {
	p.Set("created", created)
}

func (p *Ranges) Updated() types.DateTime {
	return p.GetDateTime("updated")
}

func (p *Ranges) SetUpdated(updated types.DateTime) {
	p.Set("updated", updated)
}

type TemplatesOsOptions int

const (
	TemplatesOslinux TemplatesOsOptions = iota
	TemplatesOswindows
	TemplatesOsmacos
	TemplatesOsother
)

var zzTemplatesOsOptionsSelectNameMap = map[string]TemplatesOsOptions{
	"linux":   0,
	"windows": 1,
	"macos":   2,
	"other":   3,
}
var zzTemplatesOsOptionsSelectIotaMap = map[TemplatesOsOptions]string{
	0: "linux",
	1: "windows",
	2: "macos",
	3: "other",
}

type Templates struct {
	core.BaseRecordProxy
}

func (p *Templates) CollectionName() string {
	return "templates"
}

func (p *Templates) Name() string {
	return p.GetString("name")
}

func (p *Templates) SetName(name string) {
	p.Set("name", name)
}

func (p *Templates) Os() TemplatesOsOptions {
	option := p.GetString("os")
	i, ok := zzTemplatesOsOptionsSelectNameMap[option]
	if !ok {
		panic("Unknown select value")
	}
	return i
}

func (p *Templates) SetOs(os TemplatesOsOptions) {
	i, ok := zzTemplatesOsOptionsSelectIotaMap[os]
	if !ok {
		panic("Unknown select value")
	}
	p.Set("os", i)
}

func (p *Templates) Icon() string {
	return p.GetString("icon")
}

func (p *Templates) SetIcon(icon string) {
	p.Set("icon", icon)
}

func (p *Templates) Description() string {
	return p.GetString("description")
}

func (p *Templates) SetDescription(description string) {
	p.Set("description", description)
}

func (p *Templates) Owner() *Users {
	var proxy *Users
	if rel := p.ExpandedOne("owner"); rel != nil {
		proxy = &Users{}
		proxy.Record = rel
	}
	return proxy
}

func (p *Templates) SetOwner(owner *Users) {
	var id string
	if owner != nil {
		id = owner.Id
	}
	p.Record.Set("owner", id)
	e := p.Expand()
	if owner != nil {
		e["owner"] = owner.Record
	} else {
		delete(e, "owner")
	}
	p.SetExpand(e)
}

func (p *Templates) Shared() bool {
	return p.GetBool("shared")
}

func (p *Templates) SetShared(shared bool) {
	p.Set("shared", shared)
}

func (p *Templates) Created() types.DateTime {
	return p.GetDateTime("created")
}

func (p *Templates) SetCreated(created types.DateTime) {
	p.Set("created", created)
}

func (p *Templates) Updated() types.DateTime {
	return p.GetDateTime("updated")
}

func (p *Templates) SetUpdated(updated types.DateTime) {
	p.Set("updated", updated)
}

type Users struct {
	core.BaseRecordProxy
}

func (p *Users) CollectionName() string {
	return "users"
}

func (p *Users) Name() string {
	return p.GetString("name")
}

func (p *Users) SetName(name string) {
	p.Set("name", name)
}

func (p *Users) Avatar() string {
	return p.GetString("avatar")
}

func (p *Users) SetAvatar(avatar string) {
	p.Set("avatar", avatar)
}

func (p *Users) Created() types.DateTime {
	return p.GetDateTime("created")
}

func (p *Users) SetCreated(created types.DateTime) {
	p.Set("created", created)
}

func (p *Users) Updated() types.DateTime {
	return p.GetDateTime("updated")
}

func (p *Users) SetUpdated(updated types.DateTime) {
	p.Set("updated", updated)
}

func (p *Users) UserId() string {
	return p.GetString("userID")
}

func (p *Users) SetUserId(userId string) {
	p.Set("userID", userId)
}

func (p *Users) UserNumber() int {
	return p.GetInt("userNumber")
}

func (p *Users) SetUserNumber(userNumber int) {
	p.Set("userNumber", userNumber)
}

func (p *Users) LastActive() types.DateTime {
	return p.GetDateTime("lastActive")
}

func (p *Users) SetLastActive(lastActive types.DateTime) {
	p.Set("lastActive", lastActive)
}

func (p *Users) IsAdmin() bool {
	return p.GetBool("isAdmin")
}

func (p *Users) SetIsAdmin(isAdmin bool) {
	p.Set("isAdmin", isAdmin)
}

func (p *Users) HashedApikey() string {
	return p.GetString("hashedAPIKey")
}

func (p *Users) SetHashedApikey(hashedApikey string) {
	p.Set("hashedAPIKey", hashedApikey)
}

func (p *Users) ProxmoxUsername() string {
	return p.GetString("proxmoxUsername")
}

func (p *Users) SetProxmoxUsername(proxmoxUsername string) {
	p.Set("proxmoxUsername", proxmoxUsername)
}

func (p *Users) ProxmoxPassword() string {
	return p.GetString("proxmoxPassword")
}

func (p *Users) SetProxmoxPassword(proxmoxPassword string) {
	p.Set("proxmoxPassword", proxmoxPassword)
}

func (p *Users) ProxmoxRealm() string {
	return p.GetString("proxmoxRealm")
}

func (p *Users) SetProxmoxRealm(proxmoxRealm string) {
	p.Set("proxmoxRealm", proxmoxRealm)
}

func (p *Users) ProxmoxTokenId() string {
	return p.GetString("proxmoxTokenID")
}

func (p *Users) SetProxmoxTokenId(proxmoxTokenId string) {
	p.Set("proxmoxTokenID", proxmoxTokenId)
}

func (p *Users) ProxmoxTokenSecret() string {
	return p.GetString("proxmoxTokenSecret")
}

func (p *Users) SetProxmoxTokenSecret(proxmoxTokenSecret string) {
	p.Set("proxmoxTokenSecret", proxmoxTokenSecret)
}

func (p *Users) QuotaRam() int {
	return p.GetInt("quotaRAM")
}

func (p *Users) SetQuotaRam(quotaRam int) {
	p.Set("quotaRAM", quotaRam)
}

func (p *Users) QuotaCpu() int {
	return p.GetInt("quotaCPU")
}

func (p *Users) SetQuotaCpu(quotaCpu int) {
	p.Set("quotaCPU", quotaCpu)
}

func (p *Users) QuotaStorage() int {
	return p.GetInt("quotaStorage")
}

func (p *Users) SetQuotaStorage(quotaStorage int) {
	p.Set("quotaStorage", quotaStorage)
}

func (p *Users) QuotaVms() int {
	return p.GetInt("quotaVMs")
}

func (p *Users) SetQuotaVms(quotaVms int) {
	p.Set("quotaVMs", quotaVms)
}

func (p *Users) QuotaRanges() int {
	return p.GetInt("quotaRanges")
}

func (p *Users) SetQuotaRanges(quotaRanges int) {
	p.Set("quotaRanges", quotaRanges)
}

func (p *Users) DefaultRangeId() string {
	return p.GetString("defaultRangeID")
}

func (p *Users) SetDefaultRangeId(defaultRangeId string) {
	p.Set("defaultRangeID", defaultRangeId)
}

func (p *Users) Ranges() []*Ranges {
	rels := p.ExpandedAll("ranges")
	proxies := make([]*Ranges, len(rels))
	for i := range len(rels) {
		proxies[i] = &Ranges{}
		proxies[i].Record = rels[i]
	}
	return proxies
}

func (p *Users) SetRanges(ranges []*Ranges) {
	records := make([]*core.Record, len(ranges))
	ids := make([]string, len(ranges))
	for i, r := range ranges {
		records[i] = r.Record
		ids[i] = r.Record.Id
	}
	p.Record.Set("ranges", ids)
	e := p.Expand()
	e["ranges"] = records
	p.SetExpand(e)
}

func (p *Users) Groups() []*Groups {
	rels := p.ExpandedAll("groups")
	proxies := make([]*Groups, len(rels))
	for i := range len(rels) {
		proxies[i] = &Groups{}
		proxies[i].Record = rels[i]
	}
	return proxies
}

func (p *Users) SetGroups(groups []*Groups) {
	records := make([]*core.Record, len(groups))
	ids := make([]string, len(groups))
	for i, r := range groups {
		records[i] = r.Record
		ids[i] = r.Record.Id
	}
	p.Record.Set("groups", ids)
	e := p.Expand()
	e["groups"] = records
	p.SetExpand(e)
}

type VMs struct {
	core.BaseRecordProxy
}

func (p *VMs) CollectionName() string {
	return "vms"
}

func (p *VMs) ProxmoxId() int {
	return p.GetInt("proxmoxID")
}

func (p *VMs) SetProxmoxId(proxmoxId int) {
	p.Set("proxmoxID", proxmoxId)
}

func (p *VMs) Range() *Ranges {
	var proxy *Ranges
	if rel := p.ExpandedOne("range"); rel != nil {
		proxy = &Ranges{}
		proxy.Record = rel
	}
	return proxy
}

func (p *VMs) SetRange(range_ *Ranges) {
	var id string
	if range_ != nil {
		id = range_.Id
	}
	p.Record.Set("range", id)
	e := p.Expand()
	if range_ != nil {
		e["range"] = range_.Record
	} else {
		delete(e, "range")
	}
	p.SetExpand(e)
}

func (p *VMs) Name() string {
	return p.GetString("name")
}

func (p *VMs) SetName(name string) {
	p.Set("name", name)
}

func (p *VMs) PoweredOn() bool {
	return p.GetBool("poweredOn")
}

func (p *VMs) SetPoweredOn(poweredOn bool) {
	p.Set("poweredOn", poweredOn)
}

func (p *VMs) Ip() string {
	return p.GetString("ip")
}

func (p *VMs) SetIp(ip string) {
	p.Set("ip", ip)
}

func (p *VMs) IsRouter() bool {
	return p.GetBool("isRouter")
}

func (p *VMs) SetIsRouter(isRouter bool) {
	p.Set("isRouter", isRouter)
}

func (p *VMs) Cpu() int {
	return p.GetInt("cpu")
}

func (p *VMs) SetCpu(cpu int) {
	p.Set("cpu", cpu)
}

func (p *VMs) Ram() int {
	return p.GetInt("ram")
}

func (p *VMs) SetRam(ram int) {
	p.Set("ram", ram)
}

func (p *VMs) Created() types.DateTime {
	return p.GetDateTime("created")
}

func (p *VMs) SetCreated(created types.DateTime) {
	p.Set("created", created)
}

func (p *VMs) Updated() types.DateTime {
	return p.GetDateTime("updated")
}

func (p *VMs) SetUpdated(updated types.DateTime) {
	p.Set("updated", updated)
}
