ansible_connection: ssh
ludus_template_user: root
ludus_template_password: root
ansible_user: "{{ defaults.cert_auth_linux_user | default(ludus_template_user, true) if defaults.use_cert_auth | default(false) else ludus_template_user }}"
ansible_ssh_pass: "{{ none if defaults.use_cert_auth | default(false) else ludus_template_password }}"
ansible_ssh_private_key_file: "{{ ludus_ssh_private_key_path if defaults.use_cert_auth | default(false) else '' }}"
ansible_become: "{{ defaults.use_cert_auth | default(false) and ansible_user != 'root' }}"
ansible_become_method: sudo
ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
ansible_ssh_extra_args: "{{ '-o IdentitiesOnly=yes -o PasswordAuthentication=no -o KbdInteractiveAuthentication=no' if defaults.use_cert_auth | default(false) else '' }}"
