ansible_connection: "{{ 'ssh' if defaults.use_cert_auth | default(false) else 'winrm' }}"
ansible_port: "{{ 22 if defaults.use_cert_auth | default(false) else 5986 }}"
ansible_shell_type: powershell
ansible_become_method: runas
ludus_template_user: localuser
ludus_template_password: password
ansible_user: "{{ defaults.cert_auth_windows_user | default(ludus_template_user, true) if defaults.use_cert_auth | default(false) else ludus_template_user }}"
ansible_password: "{{ none if defaults.use_cert_auth | default(false) else ludus_template_password }}"
ansible_ssh_pass: "{{ none if defaults.use_cert_auth | default(false) else ludus_template_password }}"
ansible_ssh_private_key_file: "{{ ludus_ssh_private_key_path if defaults.use_cert_auth | default(false) else '' }}"
ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
ansible_ssh_extra_args: "{{ '-o IdentitiesOnly=yes -o PasswordAuthentication=no -o KbdInteractiveAuthentication=no' if defaults.use_cert_auth | default(false) else '' }}"
ansible_winrm_transport: ssl
ansible_winrm_scheme: https
ansible_winrm_server_cert_validation: ignore
win_async_startup_timeout: 3600 # Prevent timeouts, see https://docs.ansible.com/ansible/latest/reference_appendices/config.html#win-async-startup-timeout
ansible_winrm_operation_timeout_sec: 240
ansible_winrm_read_timeout_sec: 320
