// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package dto

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for LicenseDataObjectEdition.
const (
	Community    LicenseDataObjectEdition = "community"
	Enterprise   LicenseDataObjectEdition = "enterprise"
	Professional LicenseDataObjectEdition = "professional"
)

// Defines values for AntiSandboxEnableJSONBodyVendor.
const (
	Dell   AntiSandboxEnableJSONBodyVendor = "Dell"
	Google AntiSandboxEnableJSONBodyVendor = "Google"
	HP     AntiSandboxEnableJSONBodyVendor = "HP"
	IBM    AntiSandboxEnableJSONBodyVendor = "IBM"
	Lenovo AntiSandboxEnableJSONBodyVendor = "Lenovo"
)

// AllowPayload defines model for AllowPayload.
type AllowPayload struct {
	Domains *[]Domain `json:"domains,omitempty"`
	Ips     *[]IP     `json:"ips,omitempty"`
}

// Domain A domain to allow during testing (along with HTTPS CRL domains)
type Domain = string

// ErrorInfo defines model for ErrorInfo.
type ErrorInfo struct {
	// Error Error message
	Error *string `json:"error,omitempty"`

	// Vmid The VMID of the VM
	Vmid *int32 `json:"vmid,omitempty"`

	// Vmname The name of the VM
	Vmname *string `json:"vmname,omitempty"`
}

// IP defines model for IP.
type IP = string

// LicenseDataObject defines model for LicenseDataObject.
type LicenseDataObject struct {
	// Active Whether the license is active
	Active *bool `json:"active,omitempty"`

	// Edition The type of license the Ludus server is using
	Edition *LicenseDataObjectEdition `json:"edition,omitempty"`

	// ExpiresAt The date and time the license expires
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// LicensedTo The name of the person or organization the license is licensed to
	LicensedTo *string `json:"licensed_to,omitempty"`

	// Message The message associated with the license
	Message *string `json:"message,omitempty"`
}

// LicenseDataObjectEdition The type of license the Ludus server is using
type LicenseDataObjectEdition string

// RangeObject defines model for RangeObject.
type RangeObject struct {
	VMs            []VMObject `json:"VMs"`
	AllowedDomains *[]string  `json:"allowedDomains,omitempty"`
	AllowedIPs     *[]string  `json:"allowedIPs,omitempty"`
	Description    *string    `json:"description,omitempty"`
	LastDeployment *time.Time `json:"lastDeployment,omitempty"`
	Name           *string    `json:"name,omitempty"`
	NumberOfVMs    *int32     `json:"numberOfVMs,omitempty"`
	Purpose        *string    `json:"purpose,omitempty"`
	RangeNumber    *int32     `json:"rangeNumber,omitempty"`
	RangeState     *string    `json:"rangeState,omitempty"`
	TestingEnabled *bool      `json:"testingEnabled,omitempty"`

	// UserID Must be a unique 1-20 character alpha-numeric string.
	// Initials are commonly used.
	UserID *UserID `json:"userID,omitempty"`
}

// SnapshotCreatePayload defines model for SnapshotCreatePayload.
type SnapshotCreatePayload struct {
	// Description Snapshot Description
	Description *string `json:"description,omitempty"`

	// IncludeRAM Include RAM in the snapshot. If false, the VM will be powered off when restored to this snapshot.
	IncludeRAM *bool `json:"includeRAM,omitempty"`

	// Name Snapshot name
	Name *string `json:"name,omitempty"`

	// Vmids Array of VMIDs to snapshot, if blank all VMs in the range will be snapshotted
	Vmids *[]int32 `json:"vmids,omitempty"`
}

// SnapshotInfo defines model for SnapshotInfo.
type SnapshotInfo struct {
	// Description Description of the snapshot
	Description *string `json:"description,omitempty"`

	// IncludesRAM 1 if the snapshot includes RAM, 0 if it does not
	IncludesRAM *bool `json:"includesRAM,omitempty"`

	// Name Snapshot identifier. Value 'current' identifies the current VM
	Name *string `json:"name,omitempty"`

	// Parent Parent snapshot identifier
	Parent *string `json:"parent,omitempty"`

	// Snaptime Snapshot creation time (unix)
	Snaptime *uint `json:"snaptime,omitempty"`

	// Vmid The VMID of the VM
	Vmid *int32 `json:"vmid,omitempty"`

	// Vmname The name of the VM
	Vmname *string `json:"vmname,omitempty"`
}

// UserAPIKeyObject defines model for UserAPIKeyObject.
type UserAPIKeyObject struct {
	ApiKey *string `json:"apiKey,omitempty"`
}

// UserCredentialObject defines model for UserCredentialObject.
type UserCredentialObject struct {
	ProxmoxPassword *string `json:"proxmoxPassword,omitempty"`
	ProxmoxUsername *string `json:"proxmoxUsername,omitempty"`
}

// UserObject defines model for UserObject.
type UserObject struct {
	DateCreated     *time.Time `json:"dateCreated,omitempty"`
	DateLastActive  *time.Time `json:"dateLastActive,omitempty"`
	IsAdmin         bool       `json:"isAdmin"`
	Name            string     `json:"name"`
	ProxmoxUsername *string    `json:"proxmoxUsername,omitempty"`

	// UserID Must be a unique 1-20 character alpha-numeric string.
	// Initials are commonly used.
	UserID UserID `json:"userID"`
}

// VMObject defines model for VMObject.
type VMObject struct {
	ID *int32 `json:"ID,omitempty"`
	Ip *IP    `json:"ip,omitempty"`

	// IsRouter Indicates whether this VM is the router for the range
	IsRouter    *bool  `json:"isRouter,omitempty"`
	Name        string `json:"name"`
	PoweredOn   bool   `json:"poweredOn"`
	ProxmoxID   *int32 `json:"proxmoxID,omitempty"`
	RangeNumber *int32 `json:"rangeNumber,omitempty"`
}

// RangeID Must be a valid proxmox pool name (e.g. 'DEMO', 'my-range' or 'New_Range'). Use only letters, numbers, hyphens, and underscores.
// This is the rangeID, which is used to identify the range.
type RangeID = string

// UserID Must be a unique 1-20 character alpha-numeric string.
// Initials are commonly used.
type UserID = string

// GetRolesAndCollectionsParams defines parameters for GetRolesAndCollections.
type GetRolesAndCollectionsParams struct {
	// UserID pass an optional userID to get roles and collections for a specific user
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// InstallCollectionJSONBody defines parameters for InstallCollection.
type InstallCollectionJSONBody struct {
	Collection *string `json:"collection,omitempty"`
	Force      *bool   `json:"force,omitempty"`
	Version    *string `json:"version,omitempty"`
}

// InstallCollectionParams defines parameters for InstallCollection.
type InstallCollectionParams struct {
	// UserID pass an optional userID to install for.
	// Defaults to the user's range (admins can interact with other users' ranges)
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// InstallRoleJSONBody defines parameters for InstallRole.
type InstallRoleJSONBody struct {
	Action  *string `json:"action,omitempty"`
	Force   *bool   `json:"force,omitempty"`
	Global  *bool   `json:"global,omitempty"`
	Role    *string `json:"role,omitempty"`
	Version *string `json:"version,omitempty"`
}

// InstallRoleParams defines parameters for InstallRole.
type InstallRoleParams struct {
	// UserID pass an optional userID to install for.
	// Defaults to the user's range (admins can interact with other users' ranges)
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// InstallRoleTarMultipartBody defines parameters for InstallRoleTar.
type InstallRoleTarMultipartBody struct {
	File  *openapi_types.File `json:"file,omitempty"`
	Force *bool               `json:"force,omitempty"`
}

// InstallRoleTarParams defines parameters for InstallRoleTar.
type InstallRoleTarParams struct {
	// UserID pass an optional userID to install for.
	// Defaults to the user's range (admins can interact with other users' ranges)
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// AntiSandboxEnableJSONBody defines parameters for AntiSandboxEnable.
type AntiSandboxEnableJSONBody struct {
	// DropFiles If true, will drop a random assortment of files on the autologon_user's desktop and in the autologon_user's download folder (default false)
	DropFiles *bool `json:"dropFiles,omitempty"`

	// Persist Persist SystemBiosVersion and CPU the changes to the VMs via a non-obvious scheduled task
	Persist *bool `json:"persist,omitempty"`

	// ProcessorIdentifier The Identifier value to use for the VMs
	ProcessorIdentifier *string `json:"processorIdentifier,omitempty"`

	// ProcessorName The ProcessorNameString value to use for the VMs
	ProcessorName *string `json:"processorName,omitempty"`

	// ProcessorSpeed The ~Mhz value to use for the VMs in MHz
	ProcessorSpeed *string `json:"processorSpeed,omitempty"`

	// ProcessorVendor The VendorIdentifier value to use for the VMs (e.g. GenuineIntel or AuthenticAMD)")
	ProcessorVendor *string `json:"processorVendor,omitempty"`

	// RegisteredOrganization The string to use as the "RegisteredOrganization" at HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion
	RegisteredOrganization *string `json:"registeredOrganization,omitempty"`

	// RegisteredOwner The string to use as the "RegisteredOwner" at HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion
	RegisteredOwner *string `json:"registeredOwner,omitempty"`

	// SystemBiosVersion The SystemBiosVersion value to use for the VMs
	SystemBiosVersion *string `json:"systemBiosVersion,omitempty"`

	// Vendor The computer vendor to use for all hardware values
	Vendor *AntiSandboxEnableJSONBodyVendor `json:"vendor,omitempty"`

	// VmIDs VM IDs or names to enable anti-sandbox
	VmIDs *string `json:"vmIDs,omitempty"`
}

// AntiSandboxEnableParams defines parameters for AntiSandboxEnable.
type AntiSandboxEnableParams struct {
	// UserID pass an optional userID to act on behalf of. Only admins can provide userIDs that are not their own.
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// AntiSandboxEnableJSONBodyVendor defines parameters for AntiSandboxEnable.
type AntiSandboxEnableJSONBodyVendor string

// CreateGroupJSONBody defines parameters for CreateGroup.
type CreateGroupJSONBody struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// KmsLicenseJSONBody defines parameters for KmsLicense.
type KmsLicenseJSONBody struct {
	// ProductKey The volume license product key to license the VMs with (if blank or not sent: determine from Windows version)
	ProductKey *string `json:"productKey,omitempty"`

	// Vmids Array of VMIDs to license
	Vmids *[]int32 `json:"vmids,omitempty"`
}

// KmsLicenseParams defines parameters for KmsLicense.
type KmsLicenseParams struct {
	// UserID pass an optional userID to act on behalf of. Only admins can provide userIDs that are not their own.
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// DeleteRangeParams defines parameters for DeleteRange.
type DeleteRangeParams struct {
	// RangeID The range number to query. If not provided, uses the user's default range.
	RangeID *struct {
		// RangeID Must be a valid proxmox pool name (e.g. 'DEMO', 'my-range' or 'New_Range'). Use only letters, numbers, hyphens, and underscores.
		// This is the rangeID, which is used to identify the range.
		RangeID *RangeID `json:"rangeID,omitempty"`
	} `form:"rangeID,omitempty" json:"rangeID,omitempty"`

	// UserID The userID whose range to delete.
	// Defaults to the current user (admins can delete other users' ranges)
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`

	// Force Force deletion of the range even if it has VMs. This will also destroy all VMs.
	Force *bool `form:"force,omitempty" json:"force,omitempty"`
}

// ListRangeParams defines parameters for ListRange.
type ListRangeParams struct {
	// RangeID The range number to query. If not provided, uses the user's default range.
	RangeID *struct {
		// RangeID Must be a valid proxmox pool name (e.g. 'DEMO', 'my-range' or 'New_Range'). Use only letters, numbers, hyphens, and underscores.
		// This is the rangeID, which is used to identify the range.
		RangeID *RangeID `json:"rangeID,omitempty"`
	} `form:"rangeID,omitempty" json:"rangeID,omitempty"`

	// UserID The userID to query ranges for.
	// Defaults to the current user (admins can query other users' ranges)
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// AbortRangeParams defines parameters for AbortRange.
type AbortRangeParams struct {
	// RangeID The range number to abort deployment for. If not provided, uses the user's default range.
	RangeID *struct {
		// RangeID Must be a valid proxmox pool name (e.g. 'DEMO', 'my-range' or 'New_Range'). Use only letters, numbers, hyphens, and underscores.
		// This is the rangeID, which is used to identify the range.
		RangeID *RangeID `json:"rangeID,omitempty"`
	} `form:"rangeID,omitempty" json:"rangeID,omitempty"`

	// UserID The userID whose range deployment to abort.
	// Defaults to the current user (admins can abort other users' range deployments)
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// GetAnsibleInventoryParams defines parameters for GetAnsibleInventory.
type GetAnsibleInventoryParams struct {
	// RangeID The range number to get inventory for. If not provided, uses the user's default range.
	RangeID *struct {
		// RangeID Must be a valid proxmox pool name (e.g. 'DEMO', 'my-range' or 'New_Range'). Use only letters, numbers, hyphens, and underscores.
		// This is the rangeID, which is used to identify the range.
		RangeID *RangeID `json:"rangeID,omitempty"`
	} `form:"rangeID,omitempty" json:"rangeID,omitempty"`

	// UserID The userID to get inventory for.
	// Defaults to the current user (admins can get inventory for other users' ranges)
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// GetConfigParams defines parameters for GetConfig.
type GetConfigParams struct {
	// RangeID The range number to get config for. If not provided, uses the user's default range.
	RangeID *struct {
		// RangeID Must be a valid proxmox pool name (e.g. 'DEMO', 'my-range' or 'New_Range'). Use only letters, numbers, hyphens, and underscores.
		// This is the rangeID, which is used to identify the range.
		RangeID *RangeID `json:"rangeID,omitempty"`
	} `form:"rangeID,omitempty" json:"rangeID,omitempty"`

	// UserID The userID to get config for.
	// Defaults to the current user (admins can get config for other users' ranges)
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// PutConfigMultipartBody defines parameters for PutConfig.
type PutConfigMultipartBody struct {
	File  *openapi_types.File `json:"file,omitempty"`
	Force *bool               `json:"force,omitempty"`
}

// PutConfigParams defines parameters for PutConfig.
type PutConfigParams struct {
	// RangeID The range number to update config for. If not provided, uses the user's default range.
	RangeID *struct {
		// RangeID Must be a valid proxmox pool name (e.g. 'DEMO', 'my-range' or 'New_Range'). Use only letters, numbers, hyphens, and underscores.
		// This is the rangeID, which is used to identify the range.
		RangeID *RangeID `json:"rangeID,omitempty"`
	} `form:"rangeID,omitempty" json:"rangeID,omitempty"`

	// UserID The userID to update config for.
	// Defaults to the current user (admins can update config for other users' ranges)
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// DeployRangeJSONBody defines parameters for DeployRange.
type DeployRangeJSONBody struct {
	// Force force the deployment if testing is enabled (default: false)
	Force *bool `json:"force,omitempty"`

	// Limit limit the deploy to VM that match the specified pattern (must include localhost or no plays will run)
	Limit *string `json:"limit,omitempty"`

	// OnlyRoles limit the user defined roles to be run to this comma separated list of roles
	OnlyRoles *[]string `json:"only_roles,omitempty"`

	// Tags the ansible tags to run for this deploy (default: all)
	Tags *string `json:"tags,omitempty"`
}

// DeployRangeParams defines parameters for DeployRange.
type DeployRangeParams struct {
	// RangeID The range number to deploy. If not provided, uses the user's default range.
	RangeID *struct {
		// RangeID Must be a valid proxmox pool name (e.g. 'DEMO', 'my-range' or 'New_Range'). Use only letters, numbers, hyphens, and underscores.
		// This is the rangeID, which is used to identify the range.
		RangeID *RangeID `json:"rangeID,omitempty"`
	} `form:"rangeID,omitempty" json:"rangeID,omitempty"`

	// UserID The userID to deploy range for.
	// Defaults to the current user (admins can deploy other users' ranges)
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// GetEtcHostsParams defines parameters for GetEtcHosts.
type GetEtcHostsParams struct {
	// RangeID The range number to get hosts file for. If not provided, uses the user's default range.
	RangeID *struct {
		// RangeID Must be a valid proxmox pool name (e.g. 'DEMO', 'my-range' or 'New_Range'). Use only letters, numbers, hyphens, and underscores.
		// This is the rangeID, which is used to identify the range.
		RangeID *RangeID `json:"rangeID,omitempty"`
	} `form:"rangeID,omitempty" json:"rangeID,omitempty"`

	// UserID The userID to get hosts file for.
	// Defaults to the current user (admins can get hosts file for other users' ranges)
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// GetLogsParams defines parameters for GetLogs.
type GetLogsParams struct {
	// RangeID The range number to get logs for. If not provided, uses the user's default range.
	RangeID *struct {
		// RangeID Must be a valid proxmox pool name (e.g. 'DEMO', 'my-range' or 'New_Range'). Use only letters, numbers, hyphens, and underscores.
		// This is the rangeID, which is used to identify the range.
		RangeID *RangeID `json:"rangeID,omitempty"`
	} `form:"rangeID,omitempty" json:"rangeID,omitempty"`

	// UserID The userID to get logs for.
	// Defaults to the current user (admins can get logs for other users' ranges)
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`

	// Tail pass an optional number of lines to get
	Tail *struct {
		Tail *int `json:"tail,omitempty"`
	} `form:"tail,omitempty" json:"tail,omitempty"`

	// Cursor the line number of the last line presented to the user;
	// return lines starting at the next line (if any)
	Cursor *struct {
		Resumeline *int `json:"resumeline,omitempty"`
	} `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// PowerOffRangeJSONBody defines parameters for PowerOffRange.
type PowerOffRangeJSONBody struct {
	Machines *[]string `json:"machines,omitempty"`
}

// PowerOffRangeParams defines parameters for PowerOffRange.
type PowerOffRangeParams struct {
	// RangeID The range number to power off. If not provided, uses the user's default range.
	// Not required if specifying one or multiple machines, only used if "all" is specified.
	RangeID *struct {
		// RangeID Must be a valid proxmox pool name (e.g. 'DEMO', 'my-range' or 'New_Range'). Use only letters, numbers, hyphens, and underscores.
		// This is the rangeID, which is used to identify the range.
		RangeID *RangeID `json:"rangeID,omitempty"`
	} `form:"rangeID,omitempty" json:"rangeID,omitempty"`

	// UserID pass an optional userID to query.
	// Defaults to the user's range (admins can interact with other users' ranges)
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// PowerOnRangeJSONBody defines parameters for PowerOnRange.
type PowerOnRangeJSONBody struct {
	Machines *[]string `json:"machines,omitempty"`
}

// PowerOnRangeParams defines parameters for PowerOnRange.
type PowerOnRangeParams struct {
	// RangeID The range number to power on. If not provided, uses the user's default range.
	// Not required if specifying one or multiple machines, only used if "all" is specified.
	RangeID *struct {
		// RangeID Must be a valid proxmox pool name (e.g. 'DEMO', 'my-range' or 'New_Range'). Use only letters, numbers, hyphens, and underscores.
		// This is the rangeID, which is used to identify the range.
		RangeID *RangeID `json:"rangeID,omitempty"`
	} `form:"rangeID,omitempty" json:"rangeID,omitempty"`

	// UserID pass an optional userID to query.
	// Defaults to the user's range (admins can interact with other users' ranges)
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// GetRDPParams defines parameters for GetRDP.
type GetRDPParams struct {
	// RangeID The range number to get RDP configs for. If not provided, uses the user's default range.
	RangeID *struct {
		// RangeID Must be a valid proxmox pool name (e.g. 'DEMO', 'my-range' or 'New_Range'). Use only letters, numbers, hyphens, and underscores.
		// This is the rangeID, which is used to identify the range.
		RangeID *RangeID `json:"rangeID,omitempty"`
	} `form:"rangeID,omitempty" json:"rangeID,omitempty"`

	// UserID The userID to get RDP configs for.
	// Defaults to the current user (admins can get RDP configs for other users' ranges)
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// DeleteRangeVMsParams defines parameters for DeleteRangeVMs.
type DeleteRangeVMsParams struct {
	// UserID The userID whose range VMs to delete.
	// Defaults to the current user (admins can delete other users' range VMs)
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// CreateRangeJSONBody defines parameters for CreateRange.
type CreateRangeJSONBody struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
	Purpose     *string `json:"purpose,omitempty"`
	RangeID     *string `json:"rangeID,omitempty"`
	RangeNumber *int    `json:"rangeNumber,omitempty"`
	UserID      *string `json:"userID,omitempty"`
}

// RevokeRangeFromUserParams defines parameters for RevokeRangeFromUser.
type RevokeRangeFromUserParams struct {
	// Force Force a revocation even if the range router is not accessible
	Force *bool `form:"force,omitempty" json:"force,omitempty"`
}

// SnapshotsTakeParams defines parameters for SnapshotsTake.
type SnapshotsTakeParams struct {
	// RangeID The range number to query. If not provided, uses the user's default range.
	RangeID *struct {
		// RangeID Must be a valid proxmox pool name (e.g. 'DEMO', 'my-range' or 'New_Range'). Use only letters, numbers, hyphens, and underscores.
		// This is the rangeID, which is used to identify the range.
		RangeID *RangeID `json:"rangeID,omitempty"`
	} `form:"rangeID,omitempty" json:"rangeID,omitempty"`

	// UserID pass an optional userID to act on behalf of. Only admins can provide userIDs that are not their own.
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// GetSnapshotsParams defines parameters for GetSnapshots.
type GetSnapshotsParams struct {
	// RangeID The range number to query. If not provided, uses the user's default range.
	RangeID *struct {
		// RangeID Must be a valid proxmox pool name (e.g. 'DEMO', 'my-range' or 'New_Range'). Use only letters, numbers, hyphens, and underscores.
		// This is the rangeID, which is used to identify the range.
		RangeID *RangeID `json:"rangeID,omitempty"`
	} `form:"rangeID,omitempty" json:"rangeID,omitempty"`

	// UserID pass an optional userID to get the logs for.
	// Defaults to the user's range (admins can query other ranges)
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`

	// Vmids pass an optional comma separated list of VMIDs to get the snapshots for
	Vmids *struct {
		Vmids *string `json:"vmids,omitempty"`
	} `form:"vmids,omitempty" json:"vmids,omitempty"`
}

// SnapshotsRemoveJSONBody defines parameters for SnapshotsRemove.
type SnapshotsRemoveJSONBody struct {
	// Name Snapshot name
	Name *string `json:"name,omitempty"`

	// Vmids Array of VMIDs to snapshot, if blank all VMs in the range will be snapshotted
	Vmids *[]int32 `json:"vmids,omitempty"`
}

// SnapshotsRemoveParams defines parameters for SnapshotsRemove.
type SnapshotsRemoveParams struct {
	// RangeID The range number to query. If not provided, uses the user's default range.
	RangeID *struct {
		// RangeID Must be a valid proxmox pool name (e.g. 'DEMO', 'my-range' or 'New_Range'). Use only letters, numbers, hyphens, and underscores.
		// This is the rangeID, which is used to identify the range.
		RangeID *RangeID `json:"rangeID,omitempty"`
	} `form:"rangeID,omitempty" json:"rangeID,omitempty"`

	// UserID pass an optional userID to act on behalf of. Only admins can provide userIDs that are not their own.
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// SnapshotsRollbackJSONBody defines parameters for SnapshotsRollback.
type SnapshotsRollbackJSONBody struct {
	// Name Snapshot name
	Name *string `json:"name,omitempty"`

	// Vmids Array of VMIDs to snapshot, if blank all VMs in the range will be snapshotted
	Vmids *[]int32 `json:"vmids,omitempty"`
}

// SnapshotsRollbackParams defines parameters for SnapshotsRollback.
type SnapshotsRollbackParams struct {
	// RangeID The range number to query. If not provided, uses the user's default range.
	RangeID *struct {
		// RangeID Must be a valid proxmox pool name (e.g. 'DEMO', 'my-range' or 'New_Range'). Use only letters, numbers, hyphens, and underscores.
		// This is the rangeID, which is used to identify the range.
		RangeID *RangeID `json:"rangeID,omitempty"`
	} `form:"rangeID,omitempty" json:"rangeID,omitempty"`

	// UserID pass an optional userID to act on behalf of. Only admins can provide userIDs that are not their own.
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// DeleteTemplateParams defines parameters for DeleteTemplate.
type DeleteTemplateParams struct {
	// UserID pass an optional userID to impersonate a user (admins only)
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// BuildTemplatesJSONBody defines parameters for BuildTemplates.
type BuildTemplatesJSONBody struct {
	Parallel *int `json:"parallel,omitempty"`

	// Templates Array of template names to build. Use ["all"] to build all templates.
	Templates *[]string `json:"templates,omitempty"`
}

// AddTemplateFromTarMultipartBody defines parameters for AddTemplateFromTar.
type AddTemplateFromTarMultipartBody struct {
	File  *openapi_types.File `json:"file,omitempty"`
	Force *bool               `json:"force,omitempty"`
}

// AbortTemplatesParams defines parameters for AbortTemplates.
type AbortTemplatesParams struct {
	// UserID Pass an optional userID to kill packer processes for.
	// Defaults to the user's range (admins can interact with other users' ranges)
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// GetPackerLogsParams defines parameters for GetPackerLogs.
type GetPackerLogsParams struct {
	// UserID pass an optional userID to get the logs for.
	// Defaults to the user's range (admins can query other ranges)
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`

	// Tail pass an optional number of lines to get
	Tail *struct {
		Tail *int `json:"tail,omitempty"`
	} `form:"tail,omitempty" json:"tail,omitempty"`

	// Cursor the line number of the last line presented to the user;
	// return lines starting at the next line (if any)
	Cursor *struct {
		Resumeline *int `json:"resumeline,omitempty"`
	} `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// AllowParams defines parameters for Allow.
type AllowParams struct {
	// RangeID The range number to apply allow rules for. If not provided, uses the user's default range.
	RangeID *struct {
		// RangeID Must be a valid proxmox pool name (e.g. 'DEMO', 'my-range' or 'New_Range'). Use only letters, numbers, hyphens, and underscores.
		// This is the rangeID, which is used to identify the range.
		RangeID *RangeID `json:"rangeID,omitempty"`
	} `form:"rangeID,omitempty" json:"rangeID,omitempty"`

	// UserID pass an optional userID to act on behalf of. Only admins can provide userIDs that are not their own.
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// DenyParams defines parameters for Deny.
type DenyParams struct {
	// RangeID The range number to apply deny rules for. If not provided, uses the user's default range.
	RangeID *struct {
		// RangeID Must be a valid proxmox pool name (e.g. 'DEMO', 'my-range' or 'New_Range'). Use only letters, numbers, hyphens, and underscores.
		// This is the rangeID, which is used to identify the range.
		RangeID *RangeID `json:"rangeID,omitempty"`
	} `form:"rangeID,omitempty" json:"rangeID,omitempty"`

	// UserID pass an optional userID to act on behalf of. Only admins can provide userIDs that are not their own.
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// StartTestingParams defines parameters for StartTesting.
type StartTestingParams struct {
	// RangeID The range number to start testing for. If not provided, uses the user's default range.
	RangeID *struct {
		// RangeID Must be a valid proxmox pool name (e.g. 'DEMO', 'my-range' or 'New_Range'). Use only letters, numbers, hyphens, and underscores.
		// This is the rangeID, which is used to identify the range.
		RangeID *RangeID `json:"rangeID,omitempty"`
	} `form:"rangeID,omitempty" json:"rangeID,omitempty"`

	// UserID pass an optional userID to get the start testing for.
	// Defaults to the user's range (admins can start testing on other ranges)
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// StopTestingJSONBody defines parameters for StopTesting.
type StopTestingJSONBody struct {
	Force *bool `json:"force,omitempty"`
}

// StopTestingParams defines parameters for StopTesting.
type StopTestingParams struct {
	// RangeID The range number to stop testing for. If not provided, uses the user's default range.
	RangeID *struct {
		// RangeID Must be a valid proxmox pool name (e.g. 'DEMO', 'my-range' or 'New_Range'). Use only letters, numbers, hyphens, and underscores.
		// This is the rangeID, which is used to identify the range.
		RangeID *RangeID `json:"rangeID,omitempty"`
	} `form:"rangeID,omitempty" json:"rangeID,omitempty"`

	// UserID pass an optional userID to get the stop testing for.
	// Defaults to the user's range (admins can stop testing on other ranges)
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// UpdateJSONBody defines parameters for Update.
type UpdateJSONBody struct {
	Name *string `json:"name,omitempty"`
}

// UpdateParams defines parameters for Update.
type UpdateParams struct {
	// RangeID The range number to update. If not provided, uses the user's default range.
	RangeID *struct {
		// RangeID Must be a valid proxmox pool name (e.g. 'DEMO', 'my-range' or 'New_Range'). Use only letters, numbers, hyphens, and underscores.
		// This is the rangeID, which is used to identify the range.
		RangeID *RangeID `json:"rangeID,omitempty"`
	} `form:"rangeID,omitempty" json:"rangeID,omitempty"`

	// UserID pass an optional userID to act on behalf of. Only admins can provide userIDs that are not their own.
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// ListUserParams defines parameters for ListUser.
type ListUserParams struct {
	// UserID pass an optional userID to reset a specific user
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// AddUserJSONBody defines parameters for AddUser.
type AddUserJSONBody struct {
	Email    string `json:"email"`
	IsAdmin  bool   `json:"isAdmin"`
	Name     string `json:"name"`
	Password string `json:"password"`

	// UserID Must be a unique 1-20 character alpha-numeric string.
	// Initials are commonly used.
	UserID UserID `json:"userID"`
}

// GetAPIKeyParams defines parameters for GetAPIKey.
type GetAPIKeyParams struct {
	// UserID pass an optional userID to reset a specific user
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// GetCredentialsParams defines parameters for GetCredentials.
type GetCredentialsParams struct {
	// UserID pass an optional userID to reset a specific user
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// PostCredentialsJSONBody defines parameters for PostCredentials.
type PostCredentialsJSONBody struct {
	ProxmoxPassword *string `json:"proxmoxPassword,omitempty"`

	// UserID Must be a unique 1-20 character alpha-numeric string.
	// Initials are commonly used.
	UserID *UserID `json:"userID,omitempty"`
}

// PasswordResetJSONBody defines parameters for PasswordReset.
type PasswordResetJSONBody struct {
	// UserID Must be a unique 1-20 character alpha-numeric string.
	// Initials are commonly used.
	UserID *UserID `json:"userID,omitempty"`
}

// GetWireguardConfigParams defines parameters for GetWireguardConfig.
type GetWireguardConfigParams struct {
	// UserID pass an optional userID to reset a specific user
	UserID *struct {
		// UserID Must be a unique 1-20 character alpha-numeric string.
		// Initials are commonly used.
		UserID *UserID `json:"userID,omitempty"`
	} `form:"userID,omitempty" json:"userID,omitempty"`
}

// InstallCollectionJSONRequestBody defines body for InstallCollection for application/json ContentType.
type InstallCollectionJSONRequestBody InstallCollectionJSONBody

// InstallRoleJSONRequestBody defines body for InstallRole for application/json ContentType.
type InstallRoleJSONRequestBody InstallRoleJSONBody

// InstallRoleTarMultipartRequestBody defines body for InstallRoleTar for multipart/form-data ContentType.
type InstallRoleTarMultipartRequestBody InstallRoleTarMultipartBody

// AntiSandboxEnableJSONRequestBody defines body for AntiSandboxEnable for application/json ContentType.
type AntiSandboxEnableJSONRequestBody AntiSandboxEnableJSONBody

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody CreateGroupJSONBody

// KmsLicenseJSONRequestBody defines body for KmsLicense for application/json ContentType.
type KmsLicenseJSONRequestBody KmsLicenseJSONBody

// PutConfigMultipartRequestBody defines body for PutConfig for multipart/form-data ContentType.
type PutConfigMultipartRequestBody PutConfigMultipartBody

// DeployRangeJSONRequestBody defines body for DeployRange for application/json ContentType.
type DeployRangeJSONRequestBody DeployRangeJSONBody

// PowerOffRangeJSONRequestBody defines body for PowerOffRange for application/json ContentType.
type PowerOffRangeJSONRequestBody PowerOffRangeJSONBody

// PowerOnRangeJSONRequestBody defines body for PowerOnRange for application/json ContentType.
type PowerOnRangeJSONRequestBody PowerOnRangeJSONBody

// CreateRangeJSONRequestBody defines body for CreateRange for application/json ContentType.
type CreateRangeJSONRequestBody CreateRangeJSONBody

// SnapshotsTakeJSONRequestBody defines body for SnapshotsTake for application/json ContentType.
type SnapshotsTakeJSONRequestBody = SnapshotCreatePayload

// SnapshotsRemoveJSONRequestBody defines body for SnapshotsRemove for application/json ContentType.
type SnapshotsRemoveJSONRequestBody SnapshotsRemoveJSONBody

// SnapshotsRollbackJSONRequestBody defines body for SnapshotsRollback for application/json ContentType.
type SnapshotsRollbackJSONRequestBody SnapshotsRollbackJSONBody

// BuildTemplatesJSONRequestBody defines body for BuildTemplates for application/json ContentType.
type BuildTemplatesJSONRequestBody BuildTemplatesJSONBody

// AddTemplateFromTarMultipartRequestBody defines body for AddTemplateFromTar for multipart/form-data ContentType.
type AddTemplateFromTarMultipartRequestBody AddTemplateFromTarMultipartBody

// AllowJSONRequestBody defines body for Allow for application/json ContentType.
type AllowJSONRequestBody = AllowPayload

// DenyJSONRequestBody defines body for Deny for application/json ContentType.
type DenyJSONRequestBody = AllowPayload

// StopTestingJSONRequestBody defines body for StopTesting for application/json ContentType.
type StopTestingJSONRequestBody StopTestingJSONBody

// UpdateJSONRequestBody defines body for Update for application/json ContentType.
type UpdateJSONRequestBody UpdateJSONBody

// AddUserJSONRequestBody defines body for AddUser for application/json ContentType.
type AddUserJSONRequestBody AddUserJSONBody

// PostCredentialsJSONRequestBody defines body for PostCredentials for application/json ContentType.
type PostCredentialsJSONRequestBody PostCredentialsJSONBody

// PasswordResetJSONRequestBody defines body for PasswordReset for application/json ContentType.
type PasswordResetJSONRequestBody PasswordResetJSONBody
