ludus:
  - vm_name: deb1-CITEST
    hostname: deb1
    template: debian-11-x64-server-template
    vlan: 10
    ip_last_octet: 10
    ram_gb: 4
    cpus: 2
    linux: true
    target_node: EH-Ludus
  - vm_name: deb2-CITEST
    hostname: deb2
    template: debian-11-x64-server-template
    vlan: 10
    ip_last_octet: 11
    ram_gb: 4
    cpus: 2
    linux: true
    target_node: EH-Ludus-2

router:
  vm_name: router-CITEST
  target_node: EH-Ludus-2
